In [12]:
import pandas as pd
import geopandas as gpd
import folium
import requests

## Run source file

In [13]:
url = "https://lending.sba.gov/api/disasters/v1/declarations/"
response = requests.get(url)
print(response.status_code)

200

## Convert the API response to Python data

In [14]:
data = response.json()
type(data)

list

## find how many disasters and details of a desater

In [15]:

len(data)

362

In [16]:
data[0]

{'id': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
 'disaster_number': 'IN-20022',
 'db_physical_damage_number': 21807,
 'db_eidl_damage_number': 21808,
 'physical_damage_number': '218076',
 'eidl_damage_number': '218080',
 'major_event': None,
 'disaster_description': 'Severe Storms, Straight-line Winds, Tornadoes, and Flooding',
 'disaster_initiator': 'Governor',
 'primary_disaster_state': 'IN',
 'primary_disaster_state_display': 'Indiana',
 'primary_counties': [{'id': 720,
   'state': 'IN',
   'latitude': 40.58498,
   'longitude': -86.565141,
   'created_by': None,
   'county_name': 'Carroll',
   'fips_code_6': '18015',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 728,
   'state': 'IN',
   'latitude': 39.140897,
   'longitude': -84.975868,
   'created_by': None,
   'county_name': 'Dearborn',
   'fips_code_6': '18029',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 729,
   'state': 'IN',
   'latitude': 39.30598,
   'longitude': -85.499831,
   'created_by': None,
   'county_name': 'Decatur',
   'fips_code_6': '18031',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 730,
   'state': 'IN',
   'latitude': 40.227543,
   'longitude': -85.399262,
   'created_by': None,
   'county_name': 'Delaware',
   'fips_code_6': '18035',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 733,
   'state': 'IN',
   'latitude': 39.639655,
   'longitude': -85.185032,
   'created_by': None,
   'county_name': 'Fayette',
   'fips_code_6': '18041',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 736,
   'state': 'IN',
   'latitude': 39.409762,
   'longitude': -85.066964,
   'created_by': None,
   'county_name': 'Franklin',
   'fips_code_6': '18047',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 741,
   'state': 'IN',
   'latitude': 40.053513,
   'longitude': -86.021709,
   'created_by': None,
   'county_name': 'Hamilton',
   'fips_code_6': '18057',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 742,
   'state': 'IN',
   'latitude': 39.822529,
   'longitude': -85.77315,
   'created_by': None,
   'county_name': 'Hancock',
   'fips_code_6': '18059',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 745,
   'state': 'IN',
   'latitude': 39.929591,
   'longitude': -85.397363,
   'created_by': None,
   'county_name': 'Henry',
   'fips_code_6': '18065',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 758,
   'state': 'IN',
   'latitude': 41.472247,
   'longitude': -87.374337,
   'created_by': None,
   'county_name': 'Lake',
   'fips_code_6': '18089',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 756,
   'state': 'IN',
   'latitude': 41.549013,
   'longitude': -86.744739,
   'created_by': None,
   'county_name': 'LaPorte',
   'fips_code_6': '18091',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 760,
   'state': 'IN',
   'latitude': 40.166203,
   'longitude': -85.722454,
   'created_by': None,
   'county_name': 'Madison',
   'fips_code_6': '18095',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 761,
   'state': 'IN',
   'latitude': 39.782976,
   'longitude': -86.135794,
   'created_by': None,
   'county_name': 'Marion',
   'fips_code_6': '18097',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 767,
   'state': 'IN',
   'latitude': 39.482646,
   'longitude': -86.447457,
   'created_by': None,
   'county_name': 'Morgan',
   'fips_code_6': '18109',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 776,
   'state': 'IN',
   'latitude': 41.509914,
   'longitude': -87.071313,
   'created_by': None,
   'county_name': 'Porter',
   'fips_code_6': '18127',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 778,
   'state': 'IN',
   'latitude': 41.045272,
   'longitude': -86.692538,
   'created_by': None,
   'county_name': 'Pulaski',
   'fips_code_6': '18131',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 780,
   'state': 'IN',
   'latitude': 40.164079,
   'longitude': -85.00579,
   'created_by': None,
   'county_name': 'Randolph',
   'fips_code_6': '18135',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 782,
   'state': 'IN',
   'latitude': 39.622362,
   'longitude': -85.466529,
   'created_by': None,
   'county_name': 'Rush',
   'fips_code_6': '18139',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 792,
   'state': 'IN',
   'latitude': 40.310229,
   'longitude': -86.056207,
   'created_by': None,
   'county_name': 'Tipton',
   'fips_code_6': '18159',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 793,
   'state': 'IN',
   'latitude': 39.623111,
   'longitude': -84.925152,
   'created_by': None,
   'county_name': 'Union',
   'fips_code_6': '18161',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None},
  {'id': 801,
   'state': 'IN',
   'latitude': 39.863091,
   'longitude': -85.006735,
   'created_by': None,
   'county_name': 'Wayne',
   'fips_code_6': '18177',
   'modified_by': None,
   'county_alt_name': None,
   'additional_details': {},
   'region_office_number': '5',
   'district_office_number': '562',
   'county_alt_name_display': None}],
 'contiguous_counties': [{'id': 626,
   'state': 'IL',
   'county_name': 'Cook',
   'fips_code_6': '17031'},
  {'id': 656,
   'state': 'IL',
   'county_name': 'Kankakee',
   'fips_code_6': '17091'},
  {'id': 709, 'state': 'IL', 'county_name': 'Will', 'fips_code_6': '17197'},
  {'id': 715,
   'state': 'IN',
   'county_name': 'Bartholomew',
   'fips_code_6': '18005'},
  {'id': 717,
   'state': 'IN',
   'county_name': 'Blackford',
   'fips_code_6': '18009'},
  {'id': 718, 'state': 'IN', 'county_name': 'Boone', 'fips_code_6': '18011'},
  {'id': 719, 'state': 'IN', 'county_name': 'Brown', 'fips_code_6': '18013'},
  {'id': 721, 'state': 'IN', 'county_name': 'Cass', 'fips_code_6': '18017'},
  {'id': 724, 'state': 'IN', 'county_name': 'Clinton', 'fips_code_6': '18023'},
  {'id': 737, 'state': 'IN', 'county_name': 'Fulton', 'fips_code_6': '18049'},
  {'id': 739, 'state': 'IN', 'county_name': 'Grant', 'fips_code_6': '18053'},
  {'id': 744,
   'state': 'IN',
   'county_name': 'Hendricks',
   'fips_code_6': '18063'},
  {'id': 746, 'state': 'IN', 'county_name': 'Howard', 'fips_code_6': '18067'},
  {'id': 749, 'state': 'IN', 'county_name': 'Jasper', 'fips_code_6': '18073'},
  {'id': 750, 'state': 'IN', 'county_name': 'Jay', 'fips_code_6': '18075'},
  {'id': 752,
   'state': 'IN',
   'county_name': 'Jennings',
   'fips_code_6': '18079'},
  {'id': 753, 'state': 'IN', 'county_name': 'Johnson', 'fips_code_6': '18081'},
  {'id': 762,
   'state': 'IN',
   'county_name': 'Marshall',
   'fips_code_6': '18099'},
  {'id': 765, 'state': 'IN', 'county_name': 'Monroe', 'fips_code_6': '18105'},
  {'id': 768, 'state': 'IN', 'county_name': 'Newton', 'fips_code_6': '18111'},
  {'id': 770, 'state': 'IN', 'county_name': 'Ohio', 'fips_code_6': '18115'},
  {'id': 772, 'state': 'IN', 'county_name': 'Owen', 'fips_code_6': '18119'},
  {'id': 779, 'state': 'IN', 'county_name': 'Putnam', 'fips_code_6': '18133'},
  {'id': 781, 'state': 'IN', 'county_name': 'Ripley', 'fips_code_6': '18137'},
  {'id': 784, 'state': 'IN', 'county_name': 'Shelby', 'fips_code_6': '18145'},
  {'id': 786,
   'state': 'IN',
   'county_name': 'St. Joseph',
   'fips_code_6': '18141'},
  {'id': 787, 'state': 'IN', 'county_name': 'Starke', 'fips_code_6': '18149'},
  {'id': 791,
   'state': 'IN',
   'county_name': 'Tippecanoe',
   'fips_code_6': '18157'},
  {'id': 803, 'state': 'IN', 'county_name': 'White', 'fips_code_6': '18181'},
  {'id': 1016, 'state': 'KY', 'county_name': 'Boone', 'fips_code_6': '21015'},
  {'id': 1257,
   'state': 'MI',
   'county_name': 'Berrien',
   'fips_code_6': '26021'},
  {'id': 2068, 'state': 'OH', 'county_name': 'Butler', 'fips_code_6': '39017'},
  {'id': 2078, 'state': 'OH', 'county_name': 'Darke', 'fips_code_6': '39037'},
  {'id': 2090,
   'state': 'OH',
   'county_name': 'Hamilton',
   'fips_code_6': '39061'},
  {'id': 2127,
   'state': 'OH',
   'county_name': 'Preble',
   'fips_code_6': '39135'}],
 'tribal_regions': [],
 'damage_type_code': '6',
 'damage_type_code_display': '6 - FLOODS',
 'contact_person': None,
 'declaration_type': 3,
 'disaster_status': 11,
 'declaration_type_display': 'Presidential-Individual Assistance',
 'disaster_status_display': 'Disaster Declared',
 'fema_number': '4933',
 'usda_agency_number': '',
 'incident_start_date': '2026-08-11',
 'incident_end_date': None,
 'request_date': '2026-08-20',
 'received_date': '2026-08-26',
 'physical_declaration_number': '218076',
 'physical_deadline_date': '2026-10-25',
 'physical_unsecured_limit': 50000.0,
 'eidl_declaration_number': '218080',
 'eidl_deadline_date': '2027-05-25',
 'eidl_unsecured_limit': 50000.0,
 'declaration_date': '2026-08-25',
 'disbursement_period_months': 6,
 'grace_period_days': 60,
 'payment_deferment_period_months': 11,
 'first_payment_due_months': 12,
 'naics_code_set': None,
 'interest_rate': {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.625},
  'DL_HOME': {'low_rate': 3.0, 'high_rate': 6.0},
  'DL_BUSINESS': {'low_rate': 4.0, 'high_rate': 8.0},
  'DL_SEIDL_NP': {'low_rate': 3.625, 'high_rate': None},
  'DL_SEIDL_BUSINESS': {'low_rate': 4.0, 'high_rate': None}},
 'document_data': {'605-Package': {'documents': ['a5160e6b-6a5e-4013-bb20-e811a52ba6c6',
    '248ef0fd-1c6b-43b4-b412-8d0eba43192a'],
   'docusign_status': 'ESIGN_COMPLETED'},
  '987-Package': {'documents': []},
  'Disaster-Documents': {'documents': ['b45604ac-e6fa-4ad0-868f-c039f5461846',
    'd9cd14e7-82db-44b8-8716-eda5a97b628a',
    '9e1fe7ce-97a3-4725-81ad-0796e64fb330',
    'a5160e6b-6a5e-4013-bb20-e811a52ba6c6',
    'f9193fd8-4ec1-44a8-a3ec-c0b5286423de',
    '5b69a399-ee66-4432-bc47-ee5c2897e86d',
    '31c5f1f7-2452-40be-a11d-a72ad8746a12',
    '248ef0fd-1c6b-43b4-b412-8d0eba43192a']}},
 'documents': [{'id': 'd9cd14e7-82db-44b8-8716-eda5a97b628a',
   'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/d9cd14e7-82db-44b8-8716-eda5a97b628a/download',
   'name': 'IN-20022-01 #21807 Press Release',
   'document_type': {'available_tags': [],
    'bucket': 'disaster',
    'category': None,
    'description': 'Official notice of the disaster for the press',
    'id': 19,
    'is_public': True,
    'label': 'Press Release',
    'name': 'Press Release',
    'document_groups': [],
    'roles': [],
    'copilot_validations': None,
    'document_similarity_threshold': None,
    'face_similarity_threshold': None},
   'source': 'Lender',
   'created_by': 'rtsaunde',
   'created': '2026-08-31T14:12:33.479954-04:00',
   'modified': '2026-08-31T14:12:44.994665-04:00',
   'status': 'accepted',
   'status_changed': '2026-08-31T14:12:33.479744-04:00',
   'is_removed': False,
   'deleted_at': None,
   'copied_data': None,
   'authorization_context': {},
   'description': 'Official notice of the disaster for the press',
   'requirement_level': 'optional',
   'visibility': 'public',
   'details': {},
   'context': {},
   'document_tags': None,
   '_metadata': {'exif': {}},
   'deleted_by': None,
   'copied_from': None,
   'document_template': None,
   'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
   'service_request': None},
  {'id': '9e1fe7ce-97a3-4725-81ad-0796e64fb330',
   'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/9e1fe7ce-97a3-4725-81ad-0796e64fb330/download',
   'name': 'IN-20022 #21807 Disaster Declaration',
   'document_type': {'available_tags': [],
    'bucket': 'disaster',
    'category': None,
    'description': '',
    'id': 215,
    'is_public': True,
    'label': 'Disaster Declaration Document',
    'name': 'Disaster Declaration',
    'document_groups': [],
    'roles': [],
    'copilot_validations': None,
    'document_similarity_threshold': None,
    'face_similarity_threshold': None},
   'source': 'Lender',
   'created_by': 'FusionW14@',
   'created': '2026-08-26T16:03:31.427616-04:00',
   'modified': '2026-08-26T16:03:34.989283-04:00',
   'status': 'accepted',
   'status_changed': '2026-08-26T16:03:31.427420-04:00',
   'is_removed': False,
   'deleted_at': None,
   'copied_data': None,
   'authorization_context': {},
   'description': '',
   'requirement_level': 'optional',
   'visibility': 'public',
   'details': {},
   'context': {},
   'document_tags': None,
   '_metadata': {'exif': {}},
   'deleted_by': None,
   'copied_from': None,
   'document_template': None,
   'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
   'service_request': None},
  {'id': 'b45604ac-e6fa-4ad0-868f-c039f5461846',
   'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/b45604ac-e6fa-4ad0-868f-c039f5461846/download',
   'name': 'IN-20022 #21807 Fact Sheet',
   'document_type': {'available_tags': [],
    'bucket': 'disaster',
    'category': None,
    'description': '',
    'id': 215,
    'is_public': True,
    'label': 'Disaster Declaration Document',
    'name': 'Disaster Declaration',
    'document_groups': [],
    'roles': [],
    'copilot_validations': None,
    'document_similarity_threshold': None,
    'face_similarity_threshold': None},
   'source': 'Lender',
   'created_by': 'FusionW14@',
   'created': '2026-08-26T16:04:56.741472-04:00',
   'modified': '2026-08-26T16:05:00.338239-04:00',
   'status': 'accepted',
   'status_changed': '2026-08-26T16:04:56.741220-04:00',
   'is_removed': False,
   'deleted_at': None,
   'copied_data': None,
   'authorization_context': {},
   'description': '',
   'requirement_level': 'optional',
   'visibility': 'public',
   'details': {},
   'context': {},
   'document_tags': None,
   '_metadata': {'exif': {}},
   'deleted_by': None,
   'copied_from': None,
   'document_template': None,
   'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
   'service_request': None}],
 'major_event_display': None,
 'source': 'ULP',
 'source_external_files': [],
 'is_ulp_serviced': True,
 'is_physical_available': True,
 'search_map_url': None}

In [17]:
type(data[0])

dict

In [18]:
print(data[:1])

[{'id': '347da25a-ac1b-47b2-b0cf-6a81509a86ba', 'disaster_number': 'IN-20022', 'db_physical_damage_number': 21807, 'db_eidl_damage_number': 21808, 'physical_damage_number': '218076', 'eidl_damage_number': '218080', 'major_event': None, 'disaster_description': 'Severe Storms, Straight-line Winds, Tornadoes, and Flooding', 'disaster_initiator': 'Governor', 'primary_disaster_state': 'IN', 'primary_disaster_state_display': 'Indiana', 'primary_counties': [{'id': 720, 'state': 'IN', 'latitude': 40.58498, 'longitude': -86.565141, 'created_by': None, 'county_name': 'Carroll', 'fips_code_6': '18015', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 728, 'state': 'IN', 'latitude': 39.140897, 'longitude': -84.975868, 'created_by': None, 'county_name': 'Dearborn', 'fips_code_6': '18029', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 729, 'state': 'IN', 'latitude': 39.30598, 'longitude': -85.499831, 'created_by': None, 'county_name': 'Decatur', 'fips_code_6': '18031', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 730, 'state': 'IN', 'latitude': 40.227543, 'longitude': -85.399262, 'created_by': None, 'county_name': 'Delaware', 'fips_code_6': '18035', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 733, 'state': 'IN', 'latitude': 39.639655, 'longitude': -85.185032, 'created_by': None, 'county_name': 'Fayette', 'fips_code_6': '18041', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 736, 'state': 'IN', 'latitude': 39.409762, 'longitude': -85.066964, 'created_by': None, 'county_name': 'Franklin', 'fips_code_6': '18047', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 741, 'state': 'IN', 'latitude': 40.053513, 'longitude': -86.021709, 'created_by': None, 'county_name': 'Hamilton', 'fips_code_6': '18057', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 742, 'state': 'IN', 'latitude': 39.822529, 'longitude': -85.77315, 'created_by': None, 'county_name': 'Hancock', 'fips_code_6': '18059', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 745, 'state': 'IN', 'latitude': 39.929591, 'longitude': -85.397363, 'created_by': None, 'county_name': 'Henry', 'fips_code_6': '18065', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 758, 'state': 'IN', 'latitude': 41.472247, 'longitude': -87.374337, 'created_by': None, 'county_name': 'Lake', 'fips_code_6': '18089', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 756, 'state': 'IN', 'latitude': 41.549013, 'longitude': -86.744739, 'created_by': None, 'county_name': 'LaPorte', 'fips_code_6': '18091', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 760, 'state': 'IN', 'latitude': 40.166203, 'longitude': -85.722454, 'created_by': None, 'county_name': 'Madison', 'fips_code_6': '18095', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 761, 'state': 'IN', 'latitude': 39.782976, 'longitude': -86.135794, 'created_by': None, 'county_name': 'Marion', 'fips_code_6': '18097', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 767, 'state': 'IN', 'latitude': 39.482646, 'longitude': -86.447457, 'created_by': None, 'county_name': 'Morgan', 'fips_code_6': '18109', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 776, 'state': 'IN', 'latitude': 41.509914, 'longitude': -87.071313, 'created_by': None, 'county_name': 'Porter', 'fips_code_6': '18127', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 778, 'state': 'IN', 'latitude': 41.045272, 'longitude': -86.692538, 'created_by': None, 'county_name': 'Pulaski', 'fips_code_6': '18131', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 780, 'state': 'IN', 'latitude': 40.164079, 'longitude': -85.00579, 'created_by': None, 'county_name': 'Randolph', 'fips_code_6': '18135', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 782, 'state': 'IN', 'latitude': 39.622362, 'longitude': -85.466529, 'created_by': None, 'county_name': 'Rush', 'fips_code_6': '18139', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 792, 'state': 'IN', 'latitude': 40.310229, 'longitude': -86.056207, 'created_by': None, 'county_name': 'Tipton', 'fips_code_6': '18159', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 793, 'state': 'IN', 'latitude': 39.623111, 'longitude': -84.925152, 'created_by': None, 'county_name': 'Union', 'fips_code_6': '18161', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}, {'id': 801, 'state': 'IN', 'latitude': 39.863091, 'longitude': -85.006735, 'created_by': None, 'county_name': 'Wayne', 'fips_code_6': '18177', 'modified_by': None, 'county_alt_name': None, 'additional_details': {}, 'region_office_number': '5', 'district_office_number': '562', 'county_alt_name_display': None}], 'contiguous_counties': [{'id': 626, 'state': 'IL', 'county_name': 'Cook', 'fips_code_6': '17031'}, {'id': 656, 'state': 'IL', 'county_name': 'Kankakee', 'fips_code_6': '17091'}, {'id': 709, 'state': 'IL', 'county_name': 'Will', 'fips_code_6': '17197'}, {'id': 715, 'state': 'IN', 'county_name': 'Bartholomew', 'fips_code_6': '18005'}, {'id': 717, 'state': 'IN', 'county_name': 'Blackford', 'fips_code_6': '18009'}, {'id': 718, 'state': 'IN', 'county_name': 'Boone', 'fips_code_6': '18011'}, {'id': 719, 'state': 'IN', 'county_name': 'Brown', 'fips_code_6': '18013'}, {'id': 721, 'state': 'IN', 'county_name': 'Cass', 'fips_code_6': '18017'}, {'id': 724, 'state': 'IN', 'county_name': 'Clinton', 'fips_code_6': '18023'}, {'id': 737, 'state': 'IN', 'county_name': 'Fulton', 'fips_code_6': '18049'}, {'id': 739, 'state': 'IN', 'county_name': 'Grant', 'fips_code_6': '18053'}, {'id': 744, 'state': 'IN', 'county_name': 'Hendricks', 'fips_code_6': '18063'}, {'id': 746, 'state': 'IN', 'county_name': 'Howard', 'fips_code_6': '18067'}, {'id': 749, 'state': 'IN', 'county_name': 'Jasper', 'fips_code_6': '18073'}, {'id': 750, 'state': 'IN', 'county_name': 'Jay', 'fips_code_6': '18075'}, {'id': 752, 'state': 'IN', 'county_name': 'Jennings', 'fips_code_6': '18079'}, {'id': 753, 'state': 'IN', 'county_name': 'Johnson', 'fips_code_6': '18081'}, {'id': 762, 'state': 'IN', 'county_name': 'Marshall', 'fips_code_6': '18099'}, {'id': 765, 'state': 'IN', 'county_name': 'Monroe', 'fips_code_6': '18105'}, {'id': 768, 'state': 'IN', 'county_name': 'Newton', 'fips_code_6': '18111'}, {'id': 770, 'state': 'IN', 'county_name': 'Ohio', 'fips_code_6': '18115'}, {'id': 772, 'state': 'IN', 'county_name': 'Owen', 'fips_code_6': '18119'}, {'id': 779, 'state': 'IN', 'county_name': 'Putnam', 'fips_code_6': '18133'}, {'id': 781, 'state': 'IN', 'county_name': 'Ripley', 'fips_code_6': '18137'}, {'id': 784, 'state': 'IN', 'county_name': 'Shelby', 'fips_code_6': '18145'}, {'id': 786, 'state': 'IN', 'county_name': 'St. Joseph', 'fips_code_6': '18141'}, {'id': 787, 'state': 'IN', 'county_name': 'Starke', 'fips_code_6': '18149'}, {'id': 791, 'state': 'IN', 'county_name': 'Tippecanoe', 'fips_code_6': '18157'}, {'id': 803, 'state': 'IN', 'county_name': 'White', 'fips_code_6': '18181'}, {'id': 1016, 'state': 'KY', 'county_name': 'Boone', 'fips_code_6': '21015'}, {'id': 1257, 'state': 'MI', 'county_name': 'Berrien', 'fips_code_6': '26021'}, {'id': 2068, 'state': 'OH', 'county_name': 'Butler', 'fips_code_6': '39017'}, {'id': 2078, 'state': 'OH', 'county_name': 'Darke', 'fips_code_6': '39037'}, {'id': 2090, 'state': 'OH', 'county_name': 'Hamilton', 'fips_code_6': '39061'}, {'id': 2127, 'state': 'OH', 'county_name': 'Preble', 'fips_code_6': '39135'}], 'tribal_regions': [], 'damage_type_code': '6', 'damage_type_code_display': '6 - FLOODS', 'contact_person': None, 'declaration_type': 3, 'disaster_status': 11, 'declaration_type_display': 'Presidential-Individual Assistance', 'disaster_status_display': 'Disaster Declared', 'fema_number': '4933', 'usda_agency_number': '', 'incident_start_date': '2026-08-11', 'incident_end_date': None, 'request_date': '2026-08-20', 'received_date': '2026-08-26', 'physical_declaration_number': '218076', 'physical_deadline_date': '2026-10-25', 'physical_unsecured_limit': 50000.0, 'eidl_declaration_number': '218080', 'eidl_deadline_date': '2027-05-25', 'eidl_unsecured_limit': 50000.0, 'declaration_date': '2026-08-25', 'disbursement_period_months': 6, 'grace_period_days': 60, 'payment_deferment_period_months': 11, 'first_payment_due_months': 12, 'naics_code_set': None, 'interest_rate': {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.625}, 'DL_HOME': {'low_rate': 3.0, 'high_rate': 6.0}, 'DL_BUSINESS': {'low_rate': 4.0, 'high_rate': 8.0}, 'DL_SEIDL_NP': {'low_rate': 3.625, 'high_rate': None}, 'DL_SEIDL_BUSINESS': {'low_rate': 4.0, 'high_rate': None}}, 'document_data': {'605-Package': {'documents': ['a5160e6b-6a5e-4013-bb20-e811a52ba6c6', '248ef0fd-1c6b-43b4-b412-8d0eba43192a'], 'docusign_status': 'ESIGN_COMPLETED'}, '987-Package': {'documents': []}, 'Disaster-Documents': {'documents': ['b45604ac-e6fa-4ad0-868f-c039f5461846', 'd9cd14e7-82db-44b8-8716-eda5a97b628a', '9e1fe7ce-97a3-4725-81ad-0796e64fb330', 'a5160e6b-6a5e-4013-bb20-e811a52ba6c6', 'f9193fd8-4ec1-44a8-a3ec-c0b5286423de', '5b69a399-ee66-4432-bc47-ee5c2897e86d', '31c5f1f7-2452-40be-a11d-a72ad8746a12', '248ef0fd-1c6b-43b4-b412-8d0eba43192a']}}, 'documents': [{'id': 'd9cd14e7-82db-44b8-8716-eda5a97b628a', 'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/d9cd14e7-82db-44b8-8716-eda5a97b628a/download', 'name': 'IN-20022-01 #21807 Press Release', 'document_type': {'available_tags': [], 'bucket': 'disaster', 'category': None, 'description': 'Official notice of the disaster for the press', 'id': 19, 'is_public': True, 'label': 'Press Release', 'name': 'Press Release', 'document_groups': [], 'roles': [], 'copilot_validations': None, 'document_similarity_threshold': None, 'face_similarity_threshold': None}, 'source': 'Lender', 'created_by': 'rtsaunde', 'created': '2026-08-31T14:12:33.479954-04:00', 'modified': '2026-08-31T14:12:44.994665-04:00', 'status': 'accepted', 'status_changed': '2026-08-31T14:12:33.479744-04:00', 'is_removed': False, 'deleted_at': None, 'copied_data': None, 'authorization_context': {}, 'description': 'Official notice of the disaster for the press', 'requirement_level': 'optional', 'visibility': 'public', 'details': {}, 'context': {}, 'document_tags': None, '_metadata': {'exif': {}}, 'deleted_by': None, 'copied_from': None, 'document_template': None, 'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba', 'service_request': None}, {'id': '9e1fe7ce-97a3-4725-81ad-0796e64fb330', 'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/9e1fe7ce-97a3-4725-81ad-0796e64fb330/download', 'name': 'IN-20022 #21807 Disaster Declaration', 'document_type': {'available_tags': [], 'bucket': 'disaster', 'category': None, 'description': '', 'id': 215, 'is_public': True, 'label': 'Disaster Declaration Document', 'name': 'Disaster Declaration', 'document_groups': [], 'roles': [], 'copilot_validations': None, 'document_similarity_threshold': None, 'face_similarity_threshold': None}, 'source': 'Lender', 'created_by': 'FusionW14@', 'created': '2026-08-26T16:03:31.427616-04:00', 'modified': '2026-08-26T16:03:34.989283-04:00', 'status': 'accepted', 'status_changed': '2026-08-26T16:03:31.427420-04:00', 'is_removed': False, 'deleted_at': None, 'copied_data': None, 'authorization_context': {}, 'description': '', 'requirement_level': 'optional', 'visibility': 'public', 'details': {}, 'context': {}, 'document_tags': None, '_metadata': {'exif': {}}, 'deleted_by': None, 'copied_from': None, 'document_template': None, 'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba', 'service_request': None}, {'id': 'b45604ac-e6fa-4ad0-868f-c039f5461846', 'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/b45604ac-e6fa-4ad0-868f-c039f5461846/download', 'name': 'IN-20022 #21807 Fact Sheet', 'document_type': {'available_tags': [], 'bucket': 'disaster', 'category': None, 'description': '', 'id': 215, 'is_public': True, 'label': 'Disaster Declaration Document', 'name': 'Disaster Declaration', 'document_groups': [], 'roles': [], 'copilot_validations': None, 'document_similarity_threshold': None, 'face_similarity_threshold': None}, 'source': 'Lender', 'created_by': 'FusionW14@', 'created': '2026-08-26T16:04:56.741472-04:00', 'modified': '2026-08-26T16:05:00.338239-04:00', 'status': 'accepted', 'status_changed': '2026-08-26T16:04:56.741220-04:00', 'is_removed': False, 'deleted_at': None, 'copied_data': None, 'authorization_context': {}, 'description': '', 'requirement_level': 'optional', 'visibility': 'public', 'details': {}, 'context': {}, 'document_tags': None, '_metadata': {'exif': {}}, 'deleted_by': None, 'copied_from': None, 'document_template': None, 'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba', 'service_request': None}], 'major_event_display': None, 'source': 'ULP', 'source_external_files': [], 'is_ulp_serviced': True, 'is_physical_available': True, 'search_map_url': None}]

In [19]:
print(data[0].keys())

dict_keys(['id', 'disaster_number', 'db_physical_damage_number', 'db_eidl_damage_number', 'physical_damage_number', 'eidl_damage_number', 'major_event', 'disaster_description', 'disaster_initiator', 'primary_disaster_state', 'primary_disaster_state_display', 'primary_counties', 'contiguous_counties', 'tribal_regions', 'damage_type_code', 'damage_type_code_display', 'contact_person', 'declaration_type', 'disaster_status', 'declaration_type_display', 'disaster_status_display', 'fema_number', 'usda_agency_number', 'incident_start_date', 'incident_end_date', 'request_date', 'received_date', 'physical_declaration_number', 'physical_deadline_date', 'physical_unsecured_limit', 'eidl_declaration_number', 'eidl_deadline_date', 'eidl_unsecured_limit', 'declaration_date', 'disbursement_period_months', 'grace_period_days', 'payment_deferment_period_months', 'first_payment_due_months', 'naics_code_set', 'interest_rate', 'document_data', 'documents', 'major_event_display', 'source', 'source_external_files', 'is_ulp_serviced', 'is_physical_available', 'search_map_url'])

In [20]:
print(list(data[0].keys())[:3])

['id', 'disaster_number', 'db_physical_damage_number']

In [21]:
data[:1]

[{'id': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
  'disaster_number': 'IN-20022',
  'db_physical_damage_number': 21807,
  'db_eidl_damage_number': 21808,
  'physical_damage_number': '218076',
  'eidl_damage_number': '218080',
  'major_event': None,
  'disaster_description': 'Severe Storms, Straight-line Winds, Tornadoes, and Flooding',
  'disaster_initiator': 'Governor',
  'primary_disaster_state': 'IN',
  'primary_disaster_state_display': 'Indiana',
  'primary_counties': [{'id': 720,
    'state': 'IN',
    'latitude': 40.58498,
    'longitude': -86.565141,
    'created_by': None,
    'county_name': 'Carroll',
    'fips_code_6': '18015',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 728,
    'state': 'IN',
    'latitude': 39.140897,
    'longitude': -84.975868,
    'created_by': None,
    'county_name': 'Dearborn',
    'fips_code_6': '18029',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 729,
    'state': 'IN',
    'latitude': 39.30598,
    'longitude': -85.499831,
    'created_by': None,
    'county_name': 'Decatur',
    'fips_code_6': '18031',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 730,
    'state': 'IN',
    'latitude': 40.227543,
    'longitude': -85.399262,
    'created_by': None,
    'county_name': 'Delaware',
    'fips_code_6': '18035',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 733,
    'state': 'IN',
    'latitude': 39.639655,
    'longitude': -85.185032,
    'created_by': None,
    'county_name': 'Fayette',
    'fips_code_6': '18041',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 736,
    'state': 'IN',
    'latitude': 39.409762,
    'longitude': -85.066964,
    'created_by': None,
    'county_name': 'Franklin',
    'fips_code_6': '18047',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 741,
    'state': 'IN',
    'latitude': 40.053513,
    'longitude': -86.021709,
    'created_by': None,
    'county_name': 'Hamilton',
    'fips_code_6': '18057',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 742,
    'state': 'IN',
    'latitude': 39.822529,
    'longitude': -85.77315,
    'created_by': None,
    'county_name': 'Hancock',
    'fips_code_6': '18059',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 745,
    'state': 'IN',
    'latitude': 39.929591,
    'longitude': -85.397363,
    'created_by': None,
    'county_name': 'Henry',
    'fips_code_6': '18065',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 758,
    'state': 'IN',
    'latitude': 41.472247,
    'longitude': -87.374337,
    'created_by': None,
    'county_name': 'Lake',
    'fips_code_6': '18089',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 756,
    'state': 'IN',
    'latitude': 41.549013,
    'longitude': -86.744739,
    'created_by': None,
    'county_name': 'LaPorte',
    'fips_code_6': '18091',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 760,
    'state': 'IN',
    'latitude': 40.166203,
    'longitude': -85.722454,
    'created_by': None,
    'county_name': 'Madison',
    'fips_code_6': '18095',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 761,
    'state': 'IN',
    'latitude': 39.782976,
    'longitude': -86.135794,
    'created_by': None,
    'county_name': 'Marion',
    'fips_code_6': '18097',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 767,
    'state': 'IN',
    'latitude': 39.482646,
    'longitude': -86.447457,
    'created_by': None,
    'county_name': 'Morgan',
    'fips_code_6': '18109',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 776,
    'state': 'IN',
    'latitude': 41.509914,
    'longitude': -87.071313,
    'created_by': None,
    'county_name': 'Porter',
    'fips_code_6': '18127',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 778,
    'state': 'IN',
    'latitude': 41.045272,
    'longitude': -86.692538,
    'created_by': None,
    'county_name': 'Pulaski',
    'fips_code_6': '18131',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 780,
    'state': 'IN',
    'latitude': 40.164079,
    'longitude': -85.00579,
    'created_by': None,
    'county_name': 'Randolph',
    'fips_code_6': '18135',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 782,
    'state': 'IN',
    'latitude': 39.622362,
    'longitude': -85.466529,
    'created_by': None,
    'county_name': 'Rush',
    'fips_code_6': '18139',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 792,
    'state': 'IN',
    'latitude': 40.310229,
    'longitude': -86.056207,
    'created_by': None,
    'county_name': 'Tipton',
    'fips_code_6': '18159',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 793,
    'state': 'IN',
    'latitude': 39.623111,
    'longitude': -84.925152,
    'created_by': None,
    'county_name': 'Union',
    'fips_code_6': '18161',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None},
   {'id': 801,
    'state': 'IN',
    'latitude': 39.863091,
    'longitude': -85.006735,
    'created_by': None,
    'county_name': 'Wayne',
    'fips_code_6': '18177',
    'modified_by': None,
    'county_alt_name': None,
    'additional_details': {},
    'region_office_number': '5',
    'district_office_number': '562',
    'county_alt_name_display': None}],
  'contiguous_counties': [{'id': 626,
    'state': 'IL',
    'county_name': 'Cook',
    'fips_code_6': '17031'},
   {'id': 656,
    'state': 'IL',
    'county_name': 'Kankakee',
    'fips_code_6': '17091'},
   {'id': 709, 'state': 'IL', 'county_name': 'Will', 'fips_code_6': '17197'},
   {'id': 715,
    'state': 'IN',
    'county_name': 'Bartholomew',
    'fips_code_6': '18005'},
   {'id': 717,
    'state': 'IN',
    'county_name': 'Blackford',
    'fips_code_6': '18009'},
   {'id': 718, 'state': 'IN', 'county_name': 'Boone', 'fips_code_6': '18011'},
   {'id': 719, 'state': 'IN', 'county_name': 'Brown', 'fips_code_6': '18013'},
   {'id': 721, 'state': 'IN', 'county_name': 'Cass', 'fips_code_6': '18017'},
   {'id': 724,
    'state': 'IN',
    'county_name': 'Clinton',
    'fips_code_6': '18023'},
   {'id': 737, 'state': 'IN', 'county_name': 'Fulton', 'fips_code_6': '18049'},
   {'id': 739, 'state': 'IN', 'county_name': 'Grant', 'fips_code_6': '18053'},
   {'id': 744,
    'state': 'IN',
    'county_name': 'Hendricks',
    'fips_code_6': '18063'},
   {'id': 746, 'state': 'IN', 'county_name': 'Howard', 'fips_code_6': '18067'},
   {'id': 749, 'state': 'IN', 'county_name': 'Jasper', 'fips_code_6': '18073'},
   {'id': 750, 'state': 'IN', 'county_name': 'Jay', 'fips_code_6': '18075'},
   {'id': 752,
    'state': 'IN',
    'county_name': 'Jennings',
    'fips_code_6': '18079'},
   {'id': 753,
    'state': 'IN',
    'county_name': 'Johnson',
    'fips_code_6': '18081'},
   {'id': 762,
    'state': 'IN',
    'county_name': 'Marshall',
    'fips_code_6': '18099'},
   {'id': 765, 'state': 'IN', 'county_name': 'Monroe', 'fips_code_6': '18105'},
   {'id': 768, 'state': 'IN', 'county_name': 'Newton', 'fips_code_6': '18111'},
   {'id': 770, 'state': 'IN', 'county_name': 'Ohio', 'fips_code_6': '18115'},
   {'id': 772, 'state': 'IN', 'county_name': 'Owen', 'fips_code_6': '18119'},
   {'id': 779, 'state': 'IN', 'county_name': 'Putnam', 'fips_code_6': '18133'},
   {'id': 781, 'state': 'IN', 'county_name': 'Ripley', 'fips_code_6': '18137'},
   {'id': 784, 'state': 'IN', 'county_name': 'Shelby', 'fips_code_6': '18145'},
   {'id': 786,
    'state': 'IN',
    'county_name': 'St. Joseph',
    'fips_code_6': '18141'},
   {'id': 787, 'state': 'IN', 'county_name': 'Starke', 'fips_code_6': '18149'},
   {'id': 791,
    'state': 'IN',
    'county_name': 'Tippecanoe',
    'fips_code_6': '18157'},
   {'id': 803, 'state': 'IN', 'county_name': 'White', 'fips_code_6': '18181'},
   {'id': 1016, 'state': 'KY', 'county_name': 'Boone', 'fips_code_6': '21015'},
   {'id': 1257,
    'state': 'MI',
    'county_name': 'Berrien',
    'fips_code_6': '26021'},
   {'id': 2068,
    'state': 'OH',
    'county_name': 'Butler',
    'fips_code_6': '39017'},
   {'id': 2078, 'state': 'OH', 'county_name': 'Darke', 'fips_code_6': '39037'},
   {'id': 2090,
    'state': 'OH',
    'county_name': 'Hamilton',
    'fips_code_6': '39061'},
   {'id': 2127,
    'state': 'OH',
    'county_name': 'Preble',
    'fips_code_6': '39135'}],
  'tribal_regions': [],
  'damage_type_code': '6',
  'damage_type_code_display': '6 - FLOODS',
  'contact_person': None,
  'declaration_type': 3,
  'disaster_status': 11,
  'declaration_type_display': 'Presidential-Individual Assistance',
  'disaster_status_display': 'Disaster Declared',
  'fema_number': '4933',
  'usda_agency_number': '',
  'incident_start_date': '2026-08-11',
  'incident_end_date': None,
  'request_date': '2026-08-20',
  'received_date': '2026-08-26',
  'physical_declaration_number': '218076',
  'physical_deadline_date': '2026-10-25',
  'physical_unsecured_limit': 50000.0,
  'eidl_declaration_number': '218080',
  'eidl_deadline_date': '2027-05-25',
  'eidl_unsecured_limit': 50000.0,
  'declaration_date': '2026-08-25',
  'disbursement_period_months': 6,
  'grace_period_days': 60,
  'payment_deferment_period_months': 11,
  'first_payment_due_months': 12,
  'naics_code_set': None,
  'interest_rate': {'DL_NP': {'low_rate': 3.625, 'high_rate': 3.625},
   'DL_HOME': {'low_rate': 3.0, 'high_rate': 6.0},
   'DL_BUSINESS': {'low_rate': 4.0, 'high_rate': 8.0},
   'DL_SEIDL_NP': {'low_rate': 3.625, 'high_rate': None},
   'DL_SEIDL_BUSINESS': {'low_rate': 4.0, 'high_rate': None}},
  'document_data': {'605-Package': {'documents': ['a5160e6b-6a5e-4013-bb20-e811a52ba6c6',
     '248ef0fd-1c6b-43b4-b412-8d0eba43192a'],
    'docusign_status': 'ESIGN_COMPLETED'},
   '987-Package': {'documents': []},
   'Disaster-Documents': {'documents': ['b45604ac-e6fa-4ad0-868f-c039f5461846',
     'd9cd14e7-82db-44b8-8716-eda5a97b628a',
     '9e1fe7ce-97a3-4725-81ad-0796e64fb330',
     'a5160e6b-6a5e-4013-bb20-e811a52ba6c6',
     'f9193fd8-4ec1-44a8-a3ec-c0b5286423de',
     '5b69a399-ee66-4432-bc47-ee5c2897e86d',
     '31c5f1f7-2452-40be-a11d-a72ad8746a12',
     '248ef0fd-1c6b-43b4-b412-8d0eba43192a']}},
  'documents': [{'id': 'd9cd14e7-82db-44b8-8716-eda5a97b628a',
    'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/d9cd14e7-82db-44b8-8716-eda5a97b628a/download',
    'name': 'IN-20022-01 #21807 Press Release',
    'document_type': {'available_tags': [],
     'bucket': 'disaster',
     'category': None,
     'description': 'Official notice of the disaster for the press',
     'id': 19,
     'is_public': True,
     'label': 'Press Release',
     'name': 'Press Release',
     'document_groups': [],
     'roles': [],
     'copilot_validations': None,
     'document_similarity_threshold': None,
     'face_similarity_threshold': None},
    'source': 'Lender',
    'created_by': 'rtsaunde',
    'created': '2026-08-31T14:12:33.479954-04:00',
    'modified': '2026-08-31T14:12:44.994665-04:00',
    'status': 'accepted',
    'status_changed': '2026-08-31T14:12:33.479744-04:00',
    'is_removed': False,
    'deleted_at': None,
    'copied_data': None,
    'authorization_context': {},
    'description': 'Official notice of the disaster for the press',
    'requirement_level': 'optional',
    'visibility': 'public',
    'details': {},
    'context': {},
    'document_tags': None,
    '_metadata': {'exif': {}},
    'deleted_by': None,
    'copied_from': None,
    'document_template': None,
    'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
    'service_request': None},
   {'id': '9e1fe7ce-97a3-4725-81ad-0796e64fb330',
    'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/9e1fe7ce-97a3-4725-81ad-0796e64fb330/download',
    'name': 'IN-20022 #21807 Disaster Declaration',
    'document_type': {'available_tags': [],
     'bucket': 'disaster',
     'category': None,
     'description': '',
     'id': 215,
     'is_public': True,
     'label': 'Disaster Declaration Document',
     'name': 'Disaster Declaration',
     'document_groups': [],
     'roles': [],
     'copilot_validations': None,
     'document_similarity_threshold': None,
     'face_similarity_threshold': None},
    'source': 'Lender',
    'created_by': 'FusionW14@',
    'created': '2026-08-26T16:03:31.427616-04:00',
    'modified': '2026-08-26T16:03:34.989283-04:00',
    'status': 'accepted',
    'status_changed': '2026-08-26T16:03:31.427420-04:00',
    'is_removed': False,
    'deleted_at': None,
    'copied_data': None,
    'authorization_context': {},
    'description': '',
    'requirement_level': 'optional',
    'visibility': 'public',
    'details': {},
    'context': {},
    'document_tags': None,
    '_metadata': {'exif': {}},
    'deleted_by': None,
    'copied_from': None,
    'document_template': None,
    'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
    'service_request': None},
   {'id': 'b45604ac-e6fa-4ad0-868f-c039f5461846',
    'document': '/api/disasters/v1/declarations/347da25a-ac1b-47b2-b0cf-6a81509a86ba/documents/b45604ac-e6fa-4ad0-868f-c039f5461846/download',
    'name': 'IN-20022 #21807 Fact Sheet',
    'document_type': {'available_tags': [],
     'bucket': 'disaster',
     'category': None,
     'description': '',
     'id': 215,
     'is_public': True,
     'label': 'Disaster Declaration Document',
     'name': 'Disaster Declaration',
     'document_groups': [],
     'roles': [],
     'copilot_validations': None,
     'document_similarity_threshold': None,
     'face_similarity_threshold': None},
    'source': 'Lender',
    'created_by': 'FusionW14@',
    'created': '2026-08-26T16:04:56.741472-04:00',
    'modified': '2026-08-26T16:05:00.338239-04:00',
    'status': 'accepted',
    'status_changed': '2026-08-26T16:04:56.741220-04:00',
    'is_removed': False,
    'deleted_at': None,
    'copied_data': None,
    'authorization_context': {},
    'description': '',
    'requirement_level': 'optional',
    'visibility': 'public',
    'details': {},
    'context': {},
    'document_tags': None,
    '_metadata': {'exif': {}},
    'deleted_by': None,
    'copied_from': None,
    'document_template': None,
    'disaster': '347da25a-ac1b-47b2-b0cf-6a81509a86ba',
    'service_request': None}],
  'major_event_display': None,
  'source': 'ULP',
  'source_external_files': [],
  'is_ulp_serviced': True,
  'is_physical_available': True,
  'search_map_url': None}]

In [22]:
data[6]["disaster_number"]

'PA-20037'

In [23]:
print(data[6]["primary_disaster_state"])

PA

In [24]:
print(data[3]['disaster_description'])

Severe Storms

In [25]:
print("disaster number:", data[0]["disaster_number"])
print("state:", data[0]["primary_disaster_state"])
print("description:", data[0]["disaster_description"])
print("date:", data[0]["incident_end_date"])

disaster number: IN-20022
state: IN
description: Severe Storms, Straight-line Winds, Tornadoes, and Flooding
date: None

## get county details

In [26]:
len(data[0]["primary_counties"])

21

In [27]:
data[0]["primary_counties"][0]

{'id': 720,
 'state': 'IN',
 'latitude': 40.58498,
 'longitude': -86.565141,
 'created_by': None,
 'county_name': 'Carroll',
 'fips_code_6': '18015',
 'modified_by': None,
 'county_alt_name': None,
 'additional_details': {},
 'region_office_number': '5',
 'district_office_number': '562',
 'county_alt_name_display': None}

In [28]:
type(data[0]["primary_counties"][0])

dict

In [29]:
data[0]["primary_counties"][0].keys()

dict_keys(['id', 'state', 'latitude', 'longitude', 'created_by', 'county_name', 'fips_code_6', 'modified_by', 'county_alt_name', 'additional_details', 'region_office_number', 'district_office_number', 'county_alt_name_display'])

## County names

In [30]:
data[0]["primary_counties"][0]["county_name"]

'Carroll'

In [31]:
data[0]["primary_counties"][0]["state"]

'IN'

In [32]:
data[0]["primary_counties"][0]["fips_code_6"]

'18015'

In [33]:
county=data[0]["primary_counties"][0]
print("county:", county["county_name"])
print("state:", county["state"])
print("fips:", county["fips_code_6"])
print("lat:", county["latitude"])
print("long:", county["longitude"])

county: Carroll
state: IN
fips: 18015
lat: 40.58498
long: -86.565141

## all 21 counties

In [34]:
for county in data[0]["primary_counties"]:
    print(county["county_name"])

Carroll
Dearborn
Decatur
Delaware
Fayette
Franklin
Hamilton
Hancock
Henry
Lake
LaPorte
Madison
Marion
Morgan
Porter
Pulaski
Randolph
Rush
Tipton
Union
Wayne

## from one disaster to all disasters

In [35]:
for disaster in data:
    print(disaster["disaster_number"])

IN-20022
IN-20023
PA-20040
IL-20035
WV-20027
PA-20038
PA-20037
MP-20003
MP-20004
PA-20039
MP-20002
IA-20015
IL-20031
VI-20001
PR-20004
IL-20030
AZ-20024
MS-20024
MS-20022
IL-20033
LA-20021
IL-20028
CA-20045
LA-20018
PA-20030
IL-20027
MO-20031
NV-20007
FL-20042
SD-20023
CA-20044
NY-20039
WV-20026
GA-20029
MT-20039
NE-20027
IL-20026
NY-20044
VA-20029
SD-20020
PA-20043
MA-20006
NE-20023
OR-20026
WA-20034
ND-20015
ID-20036
KS-20035
NJ-20011
ID-20032
KY-20036
NY-20043
MS-20020
MS-20023
OK-20040
KS-20037
NJ-20010
WY-20020
UT-20017
MT-20038
VA-20026
SC-20025
KY-20033
CO-20030
ID-20031
GA-20028
TX-20083
KS-20034
NC-20026
KS-20039
KS-20036
TX-20081
MO-20029
MO-20033
OK-20036
MO-20030
VA-20025
SD-20017
TN-20034
MD-20014
OK-20038
NE-20021
PA-20042
PA-20036
DE-20002
GA-20025
NY-20042
PA-20029
NJ-20009
IL-20025
WA-20032
SD-20018
MS-20021
KS-20038
ID-20029
KS-20033
UT-20018
LA-20017
CO-20029
KY-20032
KY-20037
AZ-20023
TN-20037
NC-20027
NE-20022
NM-20024
WI-20009
WI-20005
GU-20001
MP-20001
MP-20000
MI-20044
MI-20046
VA-20024
IL-20034
MD-20015
NY-20041
NC-20025
OR-20025
NE-20028
NE-20020
NY-20048
OH-20016
VA-20032
IA-20016
PA-20041
WA-20029
MO-20032
CO-20033
NM-20023
UT-20019
KS-20032
TX-20088
OR-20022
NV-20006
WY-20018
OK-20041
LA-20022
UT-20016
ID-20034
NM-20028
NC-20029
MS-20025
NY-20045
AZ-20022
LA-20020
NC-20024
OR-20024
TX-20087
TX-20086
NM-20026
CO-20031
SD-20022
VA-20028
NC-20028
VA-20027
NE-20026
NE-20024
NE-20025
ID-20035
ID-20033
TN-20035
IL-20024
HI-20014
HI-20010
IN-20019
WA-20031
MI-20043
TX-20082
ID-20028
TX-20084
OK-20039
AL-20015
DE-20001
MA-20004
MA-20005
RI-20005
PA-20028
WY-20019
SC-20023
GA-20027
AL-20013
AL-20014
GA-20026
SC-20022
OK-20035
TX-20080
AR-20040
CO-20028
LA-20016
NY-20032
MS-20019
MS-20018
LA-20013
LA-20012
LA-20014
FL-20035
FL-20032
FL-20033
FL-20034
FL-20036
KY-20034
AR-20039
FL-20037
FL-20038
FL-20039
FL-20040
TN-20031
TN-20030
TN-20032
SC-20024
CA-20040
VA-20023
SC-20021
UT-20015
AZ-20018
HI-20013
WY-20017
NV-20005
CA-20039
TN-20033
LA-20015
NC-20023
TX-20068
MT-20034
MT-20037
SD-20016
MT-20032
ID-20027
CA-20041
CA-20038
ID-20030
GA-20024
OR-20023
OR-20021
MT-20036
AK-20019
WA-20027
WA-20028
WA-20025
AL-20012
FL-20041
HI-20012
GA-20023
AL-20011
NY-20029
OK-20034
CA-20037
OK-20033
TX-20067
KY-20024
MO-20027
CO-20027
AR-20038
MO-20028
MD-20013
NM-20022
TX-20077
NH-20010
FL-20030
MN-20024
FL-20031
AZ-20019
AZ-20014
AZ-20021
AK-20016
AK-20017
AK-20021
AK-20018
IL-20023
NY-20031
VT-20009
MS-20017
CA-20043
ZZ-00021
IN-20016
OH-20015
NM-20025
AZ-20017
AZ-20013
AL-20010
GA-20022
NY-20028
VA-20022
TN-20029
WV-20023
MO-20026
MS-20016
ID-20026
NV-20004
AR-20037
ME-20010
IL-20019
WA-20026
MT-20031
VA-20031
NE-20019
ND-20014
CO-20026
VT-20010
NJ-20014
PA-20031
IL-20018
SD-20015
KS-20029
TX-20076
PA-20032
IL-20021
NH-20011
NY-20037
NJ-20015
MN-20030
MN-20027
NM-20020
MN-20022
MN-20023
KS-20031
NJ-20016
MN-20029
MT-20035
MN-20026
NY-20038
NY-20036
TX-20073
TX-20072
MN-20025
TX-20074
KS-20030
AR-20036
NY-20030
IN-20020
NJ-20012
MI-20042
MI-20041
TX-20071
PA-20027
NJ-20013
PA-20035
NH-20013
TX-20070
ME-20009
NY-20034
PA-20033
AR-20033
AR-20035
KY-20028
KY-20029
KY-20031
AR-20034
KY-20030
IN-20017
IN-20018
PA-20034
NY-20035
NY-20033
VA-20030
MO-20013
TX-20069
AR-20032
NH-20012
TX-20075
MI-20040

## put the county loop inside the disaster loop

In [36]:
for disaster in data:
    for county in disaster["primary_counties"]:
        print(
            disaster["disaster_number"],
            county["county_name"]
        )

IN-20022 Carroll
IN-20022 Dearborn
IN-20022 Decatur
IN-20022 Delaware
IN-20022 Fayette
IN-20022 Franklin
IN-20022 Hamilton
IN-20022 Hancock
IN-20022 Henry
IN-20022 Lake
IN-20022 LaPorte
IN-20022 Madison
IN-20022 Marion
IN-20022 Morgan
IN-20022 Porter
IN-20022 Pulaski
IN-20022 Randolph
IN-20022 Rush
IN-20022 Tipton
IN-20022 Union
IN-20022 Wayne
IN-20023 Delaware
IN-20023 Fayette
IN-20023 Franklin
IN-20023 Hamilton
IN-20023 Henry
IN-20023 Lake
IN-20023 LaPorte
IN-20023 Madison
IN-20023 Porter
IN-20023 Tipton
IN-20023 Wayne
PA-20040 Clearfield
IL-20035 Cook
IL-20035 Will
WV-20027 Lewis
WV-20027 Pleasants
WV-20027 Ritchie
WV-20027 Upshur
PA-20038 Philadelphia
PA-20037 Blair
MP-20003 Rota
MP-20004 Saipan
MP-20004 Tinian
PA-20039 Monroe
MP-20002 Rota
IA-20015 Polk
IL-20031 Kane
VI-20001 SAINT CROIX
VI-20001 SAINT JOHN
VI-20001 SAINT THOMAS
PR-20004 CABO ROJO
PR-20004 COAMO
PR-20004 GUANICA
PR-20004 GUAYANILLA
PR-20004 JUANA DIAZ
PR-20004 LAJAS
PR-20004 PENUELAS
PR-20004 PONCE
PR-20004 SABANA GRANDE
PR-20004 SALINAS
PR-20004 SAN GERMAN
PR-20004 SANTA ISABEL
PR-20004 YAUCO
IL-20030 Jefferson
AZ-20024 Coconino
AZ-20024 Yavapai
MS-20024 Covington
MS-20024 George
MS-20024 Greene
MS-20024 Hancock
MS-20024 Harrison
MS-20024 Pearl River
MS-20024 Stone
MS-20024 Wayne
MS-20022 Hancock
MS-20022 Harrison
MS-20022 Pearl River
MS-20022 Stone
IL-20033 Warren
LA-20021 Avoyelles
LA-20021 East Feliciana
LA-20021 Pointe Coupee
LA-20021 St. Charles
LA-20021 St. Landry
LA-20021 Winn
IL-20028 Coles
IL-20028 Effingham
CA-20045 Los Angeles
LA-20018 Avoyelles
LA-20018 Lafourche
LA-20018 Pointe Coupee
LA-20018 St. Landry
LA-20018 St. Tammany
LA-20018 Terrebonne
PA-20030 Berks
IL-20027 Cook
IL-20027 LaSalle
MO-20031 Adair
MO-20031 Andrew
MO-20031 Callaway
MO-20031 Camden
MO-20031 Cape Girardeau
MO-20031 Dade
MO-20031 Daviess
MO-20031 Gasconade
MO-20031 Gentry
MO-20031 Grundy
MO-20031 Harrison
MO-20031 Hickory
MO-20031 Holt
MO-20031 Jasper
MO-20031 Knox
MO-20031 Lewis
MO-20031 Linn
MO-20031 Macon
MO-20031 Marion
MO-20031 Mercer
MO-20031 Miller
MO-20031 Moniteau
MO-20031 Morgan
MO-20031 Newton
MO-20031 Nodaway
MO-20031 Osage
MO-20031 Polk
MO-20031 Putnam
MO-20031 Scott
MO-20031 Shelby
MO-20031 Sullivan
MO-20031 Vernon
MO-20031 Webster
MO-20031 Worth
NV-20007 Eureka
NV-20007 Lander
FL-20042 Monroe
SD-20023 Meade
CA-20044 Orange
NY-20039 Queens
WV-20026 Grant
WV-20026 Hampshire
WV-20026 Hardy
WV-20026 McDowell
WV-20026 Mercer
WV-20026 Mineral
WV-20026 Monroe
WV-20026 Pendleton
WV-20026 Raleigh
WV-20026 Randolph
WV-20026 Summers
WV-20026 Tucker
WV-20026 Wyoming
GA-20029 Richmond
MT-20039 Dawson
MT-20039 Richland
MT-20039 Roosevelt
MT-20039 Sheridan
MT-20039 Wibaux
NE-20027 Buffalo
NE-20027 Fillmore
NE-20027 Gage
NE-20027 Howard
NE-20027 Jefferson
NE-20027 Nemaha
NE-20027 Thayer
NE-20027 Thurston
IL-20026 Cook
NY-20044 Cayuga
NY-20044 Oswego
VA-20029 Tazewell
SD-20020 Lawrence
PA-20043 Bucks
PA-20043 Delaware
PA-20043 Lehigh
MA-20006 Middlesex
NE-20023 Fillmore
NE-20023 Franklin
OR-20026 Benton
OR-20026 Lake
WA-20034 Ferry
WA-20034 Okanogan
ND-20015 Golden Valley
ND-20015 McKenzie
ID-20036 Custer
KS-20035 Barber
KS-20035 Kiowa
NJ-20011 Monmouth
NJ-20011 Mercer
ID-20032 Bannock
ID-20032 Bingham
ID-20032 Bonneville
ID-20032 Butte
ID-20032 Caribou
ID-20032 Franklin
ID-20032 Fremont
ID-20032 Jefferson
ID-20032 Madison
KY-20036 Adair
KY-20036 Edmonson
KY-20036 Grayson
KY-20036 Green
KY-20036 McLean
KY-20036 Marion
KY-20036 Russell
KY-20036 Taylor
KY-20036 Wayne
NY-20043 Fulton
NY-20043 Montgomery
NY-20043 Onondaga
NY-20043 St. Lawrence
NY-20043 Otsego
MS-20020 Franklin
MS-20020 Lamar
MS-20020 Lawrence
MS-20020 Lincoln
MS-20020 Wilkinson
MS-20023 Franklin
MS-20023 Lamar
MS-20023 Lawrence
MS-20023 Lincoln
MS-20023 Wilkinson
OK-20040 Woods
KS-20037 Barton
KS-20037 Comanche
KS-20037 McPherson
KS-20037 Pawnee
KS-20037 Reno
KS-20037 Rice
KS-20037 Seward
KS-20037 Stafford
NJ-20010 Essex
WY-20020 Campbell
WY-20020 Converse
WY-20020 Goshen
WY-20020 Johnson
WY-20020 Laramie
WY-20020 Niobrara
WY-20020 Platte
WY-20020 Weston
UT-20017 Daggett
UT-20017 Piute
UT-20017 Summit
MT-20038 Beaverhead
MT-20038 Cascade
MT-20038 Chouteau
MT-20038 Glacier
MT-20038 Hill
MT-20038 Liberty
MT-20038 Madison
MT-20038 Pondera
MT-20038 Teton
MT-20038 Toole
VA-20026 Amherst
VA-20026 Appomattox
VA-20026 Buckingham
VA-20026 Campbell
VA-20026 Charlotte
VA-20026 Henry
VA-20026 Nelson
VA-20026 Pittsylvania
VA-20026 Sussex
SC-20025 Aiken
SC-20025 Barnwell
SC-20025 Calhoun
SC-20025 Florence
SC-20025 Kershaw
SC-20025 Lee
SC-20025 Lexington
SC-20025 Richland
SC-20025 Sumter
SC-20025 Clarendon
KY-20033 Barren
KY-20033 Butler
KY-20033 Casey
KY-20033 Garrard
KY-20033 Lincoln
KY-20033 Monroe
KY-20033 Ohio
KY-20033 Pulaski
KY-20033 Rockcastle
KY-20033 Warren
CO-20030 Bent
CO-20030 Prowers
ID-20031 Blaine
ID-20031 Minidoka
ID-20031 Oneida
ID-20031 Power
GA-20028 Carroll
GA-20028 Haralson
GA-20028 Jones
GA-20028 Paulding
GA-20028 Polk
TX-20083 Sherman
KS-20034 Clark
KS-20034 Hamilton
KS-20034 Sherman
KS-20034 Stanton
NC-20026 Bladen
NC-20026 Brunswick
NC-20026 Columbus
NC-20026 Forsyth
NC-20026 Hoke
NC-20026 Montgomery
NC-20026 Moore
KS-20039 Saline
KS-20036 Cherokee
KS-20036 Morris
KS-20036 Osage
KS-20036 Saline
KS-20036 Wabaunsee
TX-20081 Cameron
TX-20081 Parker
TX-20081 Victoria
TX-20081 Wise
MO-20029 Greene
MO-20033 Randolph
MO-20033 Saline
OK-20036 Garfield
MO-20030 Carroll
MO-20030 Chariton
MO-20030 Greene
MO-20030 Holt
MO-20030 Howard
MO-20030 Monroe
MO-20030 Randolph
MO-20030 Ripley
MO-20030 Saline
MO-20030 St. Francois
VA-20025 Halifax
SD-20017 Brule
SD-20017 Gregory
SD-20017 Lyman
SD-20017 Tripp
TN-20034 Cheatham
TN-20034 Chester
TN-20034 Davidson
TN-20034 Decatur
TN-20034 Dickson
TN-20034 Fentress
TN-20034 Hardeman
TN-20034 Hardin
TN-20034 Henderson
TN-20034 Hickman
TN-20034 Houston
TN-20034 Humphreys
TN-20034 Lewis
TN-20034 McNairy
TN-20034 Macon
TN-20034 Madison
TN-20034 Marion
TN-20034 Maury
TN-20034 Montgomery
TN-20034 Perry
TN-20034 Robertson
TN-20034 Sequatchie
TN-20034 Stewart
TN-20034 Sumner
TN-20034 Tipton
TN-20034 Trousdale
TN-20034 Wayne
TN-20034 Williamson
TN-20034 Wilson
MD-20014 Caroline
MD-20014 Carroll
MD-20014 Cecil
MD-20014 Dorchester
MD-20014 Frederick
MD-20014 Howard
MD-20014 Montgomery
MD-20014 Queen Anne's
MD-20014 Somerset
MD-20014 Washington
MD-20014 Wicomico
MD-20014 Baltimore County
OK-20038 Cimarron
OK-20038 Ellis
OK-20038 Woodward
NE-20021 Keya Paha
NE-20021 Logan
NE-20021 Rock
PA-20042 Allegheny
PA-20042 Beaver
PA-20042 Berks
PA-20042 Blair
PA-20042 Butler
PA-20042 Centre
PA-20042 Chester
PA-20042 Clinton
PA-20042 Huntingdon
PA-20042 Jefferson
PA-20042 Lebanon
PA-20042 Luzerne
PA-20042 McKean
PA-20042 Schuylkill
PA-20036 Bedford
PA-20036 Columbia
PA-20036 Snyder
PA-20036 Union
DE-20002 Kent
DE-20002 New Castle
DE-20002 Sussex
GA-20025 Brantley
NY-20042 Broome
NY-20042 Cayuga
NY-20042 Chemung
NY-20042 Columbia
NY-20042 Cortland
NY-20042 Dutchess
NY-20042 Fulton
NY-20042 Greene
NY-20042 Montgomery
NY-20042 Nassau
NY-20042 Niagara
NY-20042 Onondaga
NY-20042 Ontario
NY-20042 Orleans
NY-20042 Oswego
NY-20042 Putnam
NY-20042 Rockland
NY-20042 Saratoga
NY-20042 Schuyler
NY-20042 Seneca
NY-20042 Steuben
NY-20042 Suffolk
NY-20042 Tompkins
NY-20042 Ulster
NY-20042 Washington
NY-20042 Wayne
NY-20042 Westchester
NY-20042 Yates
NY-20042 Orange
PA-20029 Adams
PA-20029 Cumberland
PA-20029 Lackawanna
PA-20029 Montour
PA-20029 York
NJ-20009 Atlantic
NJ-20009 Bergen
NJ-20009 Burlington
NJ-20009 Camden
NJ-20009 Cape May
NJ-20009 Cumberland
NJ-20009 Gloucester
NJ-20009 Hunterdon
NJ-20009 Mercer
NJ-20009 Middlesex
NJ-20009 Monmouth
NJ-20009 Morris
NJ-20009 Ocean
NJ-20009 Salem
NJ-20009 Somerset
NJ-20009 Sussex
NJ-20009 Warren
IL-20025 Stephenson
WA-20032 Okanogan
SD-20018 Bennett
SD-20018 Bon Homme
SD-20018 Charles Mix
SD-20018 Clay
SD-20018 Custer
SD-20018 Fall River
SD-20018 Jackson
SD-20018 Oglala Lakota
SD-20018 Pennington
SD-20018 Turner
SD-20018 Yankton
MS-20021 George
MS-20021 Hinds
MS-20021 Warren
MS-20021 Washington
KS-20038 Edwards
KS-20038 Finney
KS-20038 Ford
KS-20038 Grant
KS-20038 Gray
KS-20038 Haskell
KS-20038 Hodgeman
KS-20038 Kearny
KS-20038 Rush
ID-20029 Cassia
ID-20029 Twin Falls
KS-20033 Decatur
KS-20033 Labette
KS-20033 Norton
KS-20033 Phillips
KS-20033 Rawlins
UT-20018 Box Elder
UT-20018 Sanpete
UT-20018 Utah
UT-20018 Wasatch
LA-20017 Allen
LA-20017 Iberia
LA-20017 Morehouse
LA-20017 Orleans
LA-20017 Ouachita
LA-20017 Plaquemines
LA-20017 St. Bernard
LA-20017 St. Charles
LA-20017 St. James
LA-20017 St. John the Baptist
LA-20017 St. Tammany
LA-20017 Union
CO-20029 Elbert
CO-20029 Kit Carson
CO-20029 Otero
CO-20029 Washington
KY-20032 Calloway
KY-20032 Carlisle
KY-20032 Fulton
KY-20032 Graves
KY-20032 Hickman
KY-20032 Marshall
KY-20037 Bell
KY-20037 Boyle
KY-20037 Breathitt
KY-20037 Breckinridge
KY-20037 Clay
KY-20037 Clinton
KY-20037 Cumberland
KY-20037 Hardin
KY-20037 Hart
KY-20037 Jackson
KY-20037 Knox
KY-20037 Larue
KY-20037 Laurel
KY-20037 Lee
KY-20037 McCreary
KY-20037 Madison
KY-20037 Mercer
KY-20037 Metcalfe
KY-20037 Nelson
KY-20037 Owsley
KY-20037 Perry
KY-20037 Washington
KY-20037 Whitley
AZ-20023 Gila
AZ-20023 Pinal
AZ-20023 Yuma
TN-20037 Anderson
TN-20037 Campbell
TN-20037 Claiborne
TN-20037 Clay
TN-20037 Jackson
TN-20037 Overton
TN-20037 Pickett
TN-20037 Putnam
TN-20037 Scott
TN-20037 Van Buren
TN-20037 White
NC-20027 Chatham
NC-20027 Durham
NC-20027 Granville
NC-20027 Scotland
NC-20027 Wake
NE-20022 Blaine
NE-20022 Brown
NE-20022 Harlan
NE-20022 Thomas
NM-20024 Union
WI-20009 Iowa
WI-20009 Jackson
WI-20009 Jefferson
WI-20009 Juneau
WI-20009 Kewaunee
WI-20009 Outagamie
WI-20009 Racine
WI-20009 Rock
WI-20009 Vernon
WI-20009 Waupaca
WI-20005 Brown
WI-20005 Buffalo
WI-20005 Jackson
WI-20005 Jefferson
WI-20005 Juneau
WI-20005 Marathon
WI-20005 Milwaukee
WI-20005 Outagamie
WI-20005 Racine
WI-20005 Rock
WI-20005 Vernon
WI-20005 Washington
WI-20005 Waukesha
WI-20005 Waupaca
WI-20005 Bayfield
WI-20005 Kenosha
WI-20005 Manitowoc
WI-20005 Sauk
WI-20005 Winnebago
GU-20001 GUAM
MP-20001 Northern Islands Municipality
MP-20001 Rota Municipality
MP-20001 Saipan Municipality
MP-20001 Tinian Municipality
MP-20000 Northern Islands Municipality
MP-20000 Rota Municipality
MP-20000 Saipan Municipality
MP-20000 Tinian Municipality
MI-20044 Alcona
MI-20044 Allegan
MI-20044 Alpena
MI-20044 Antrim
MI-20044 Barry
MI-20044 Benzie
MI-20044 Charlevoix
MI-20044 Cheboygan
MI-20044 Crawford
MI-20044 Emmet
MI-20044 Grand Traverse
MI-20044 Gratiot
MI-20044 Iosco
MI-20044 Kalamazoo
MI-20044 Kalkaska
MI-20044 Manistee
MI-20044 Mecosta
MI-20044 Montcalm
MI-20044 Muskegon
MI-20044 Newaygo
MI-20044 Oceana
MI-20044 Osceola
MI-20044 Presque Isle
MI-20044 Roscommon
MI-20044 Saginaw
MI-20044 Wexford
MI-20044 Washtenaw
MI-20046 Alcona
MI-20046 Alpena
MI-20046 Benzie
MI-20046 Charlevoix
MI-20046 Cheboygan
MI-20046 Crawford
MI-20046 Eaton
MI-20046 Emmet
MI-20046 Grand Traverse
MI-20046 Gratiot
MI-20046 Iron
MI-20046 Kalkaska
MI-20046 Lake
MI-20046 Manistee
MI-20046 Marquette
MI-20046 Mecosta
MI-20046 Menominee
MI-20046 Missaukee
MI-20046 Montmorency
MI-20046 Newaygo
MI-20046 Ogemaw
MI-20046 Osceola
MI-20046 Oscoda
MI-20046 Presque Isle
MI-20046 Roscommon
MI-20046 Tuscola
MI-20046 Wexford
VA-20024 Mecklenburg
IL-20034 Massac
IL-20034 Pope
MD-20015 Anne Arundel
MD-20015 Calvert
MD-20015 Queen Anne's
MD-20015 St. Mary's
MD-20015 Somerset
MD-20015 Worcester
NY-20041 Broome
NY-20041 Cortland
NY-20041 Tompkins
NC-20025 Ashe
NC-20025 Buncombe
NC-20025 Davidson
NC-20025 Henderson
NC-20025 Transylvania
NC-20025 Vance
NC-20025 Watauga
OR-20025 Coos
OR-20025 Curry
OR-20025 Gilliam
OR-20025 Grant
OR-20025 Harney
OR-20025 Josephine
OR-20025 Morrow
OR-20025 Wasco
NE-20028 Lancaster
NE-20028 Saline
NE-20020 Adams
NE-20020 Antelope
NE-20020 Arthur
NE-20020 Banner
NE-20020 Boone
NE-20020 Box Butte
NE-20020 Boyd
NE-20020 Buffalo
NE-20020 Butler
NE-20020 Cedar
NE-20020 Chase
NE-20020 Cherry
NE-20020 Cheyenne
NE-20020 Clay
NE-20020 Colfax
NE-20020 Dawes
NE-20020 Dawson
NE-20020 Deuel
NE-20020 Dixon
NE-20020 Dundy
NE-20020 Frontier
NE-20020 Furnas
NE-20020 Garden
NE-20020 Garfield
NE-20020 Gosper
NE-20020 Grant
NE-20020 Greeley
NE-20020 Hall
NE-20020 Hamilton
NE-20020 Hayes
NE-20020 Hitchcock
NE-20020 Holt
NE-20020 Hooker
NE-20020 Howard
NE-20020 Kearney
NE-20020 Keith
NE-20020 Kimball
NE-20020 Knox
NE-20020 Lincoln
NE-20020 Loup
NE-20020 McPherson
NE-20020 Madison
NE-20020 Merrick
NE-20020 Morrill
NE-20020 Nance
NE-20020 Perkins
NE-20020 Phelps
NE-20020 Pierce
NE-20020 Platte
NE-20020 Polk
NE-20020 Red Willow
NE-20020 Scotts Bluff
NE-20020 Seward
NE-20020 Sheridan
NE-20020 Sherman
NE-20020 Sioux
NE-20020 Valley
NE-20020 Wayne
NE-20020 Wheeler
NE-20020 York
NE-20020 Custer
NY-20048 Albany
NY-20048 Schenectady
NY-20048 Schoharie
OH-20016 Defiance
OH-20016 Hancock
OH-20016 Henry
OH-20016 Paulding
OH-20016 Putnam
OH-20016 Van Wert
OH-20016 Wood
VA-20032 Accomack
VA-20032 Alleghany
VA-20032 Amelia
VA-20032 Bath
VA-20032 Bland
VA-20032 Botetourt
VA-20032 Caroline
VA-20032 Craig
VA-20032 Culpeper
VA-20032 Dinwiddie
VA-20032 Essex
VA-20032 Fairfax County
VA-20032 Fauquier
VA-20032 Floyd
VA-20032 Giles
VA-20032 Gloucester
VA-20032 Goochland
VA-20032 Greene
VA-20032 Hanover
VA-20032 Highland
VA-20032 King and Queen
VA-20032 King George
VA-20032 King William
VA-20032 Lancaster
VA-20032 Louisa
VA-20032 Madison
VA-20032 Mathews
VA-20032 Middlesex
VA-20032 Montgomery
VA-20032 Northampton
VA-20032 Northumberland
VA-20032 Nottoway
VA-20032 Orange
VA-20032 Page
VA-20032 Powhatan
VA-20032 Prince William
VA-20032 Pulaski
VA-20032 Rappahannock
VA-20032 Richmond County
VA-20032 Rockbridge
VA-20032 Rockingham
VA-20032 Russell
VA-20032 Spotsylvania
VA-20032 Stafford
VA-20032 Westmoreland
VA-20032 Roanoke County
IA-20016 Lyon
PA-20041 Adams
PA-20041 Berks
PA-20041 Cumberland
PA-20041 Franklin
PA-20041 Fulton
WA-20029 Asotin
WA-20029 Garfield
WA-20029 Whitman
MO-20032 Cape Girardeau
MO-20032 Mississippi
MO-20032 Scott
CO-20033 Cheyenne
CO-20033 Crowley
CO-20033 Fremont
CO-20033 Kiowa
CO-20033 Morgan
NM-20023 Colfax
UT-20019 Cache
UT-20019 Davis
UT-20019 Salt Lake
UT-20019 Washington
UT-20019 Weber
KS-20032 Cheyenne
KS-20032 Meade
TX-20088 Bailey
TX-20088 Cochran
TX-20088 Nolan
OR-20022 Malheur
NV-20006 Humboldt
WY-20018 Natrona
WY-20018 Washakie
OK-20041 Alfalfa
OK-20041 Grant
LA-20022 Cameron
UT-20016 Iron
UT-20016 Kane
ID-20034 Adams
ID-20034 Benewah
ID-20034 Clark
ID-20034 Elmore
ID-20034 Gem
ID-20034 Gooding
ID-20034 Jerome
ID-20034 Kootenai
ID-20034 Lemhi
ID-20034 Lewis
ID-20034 Lincoln
ID-20034 Nez Perce
ID-20034 Teton
ID-20034 Washington
NM-20028 Curry
NM-20028 De Baca
NM-20028 Guadalupe
NM-20028 Roosevelt
NM-20028 San Miguel
NM-20028 Santa Fe
NM-20028 Torrance
NC-20029 Beaufort
NC-20029 Carteret
NC-20029 Chowan
NC-20029 Craven
NC-20029 Currituck
NC-20029 Dare
NC-20029 Hyde
NC-20029 Jones
NC-20029 Lenoir
NC-20029 New Hanover
NC-20029 Onslow
NC-20029 Pamlico
NC-20029 Tyrrell
NC-20029 Washington
MS-20025 Jackson
NY-20045 Erie
AZ-20022 Coconino
AZ-20022 Maricopa
LA-20020 Calcasieu
NC-20024 Anson
NC-20024 Graham
NC-20024 Jackson
OR-20024 Crook
OR-20024 Deschutes
OR-20024 Douglas
OR-20024 Jackson
OR-20024 Jefferson
OR-20024 Klamath
OR-20024 Lane
OR-20024 Linn
OR-20024 Marion
OR-20024 Wheeler
TX-20087 Gregg
TX-20086 Castro
TX-20086 Collingsworth
TX-20086 Deaf Smith
TX-20086 Hartley
TX-20086 Oldham
TX-20086 Parmer
NM-20026 Mora
NM-20026 Harding
NM-20026 Quay
CO-20031 Alamosa
SD-20022 Aurora
VA-20028 Albemarle
VA-20028 Amherst
VA-20028 Augusta
VA-20028 Bedford County
VA-20028 Botetourt
VA-20028 Buckingham
VA-20028 Caroline
VA-20028 Clarke
VA-20028 Culpeper
VA-20028 Cumberland
VA-20028 Dinwiddie
VA-20028 Essex
VA-20028 Fairfax County
VA-20028 Fauquier
VA-20028 Floyd
VA-20028 Fluvanna
VA-20028 Frederick
VA-20028 Giles
VA-20028 Gloucester
VA-20028 Goochland
VA-20028 Greene
VA-20028 Halifax
VA-20028 Hanover
VA-20028 Henry
VA-20028 Highland
VA-20028 Loudoun
VA-20028 Louisa
VA-20028 Madison
VA-20028 Montgomery
VA-20028 Nelson
VA-20028 New Kent
VA-20028 Orange
VA-20028 Page
VA-20028 Pittsylvania
VA-20028 Prince William
VA-20028 Pulaski
VA-20028 Rappahannock
VA-20028 Rockingham
VA-20028 Shenandoah
VA-20028 Stafford
VA-20028 Warren
VA-20028 Washington
VA-20028 Wise
NC-20028 Alleghany
NC-20028 Greene
NC-20028 Hertford
NC-20028 Pender
NC-20028 Pitt
NC-20028 Surry
NC-20028 Wayne
VA-20027 Albemarle
VA-20027 Augusta
VA-20027 Bedford County
VA-20027 Franklin County
VA-20027 Fluvanna
VA-20027 Cumberland
VA-20027 Carroll
VA-20027 Grayson
VA-20027 Lunenburg
VA-20027 Patrick
VA-20027 Prince Edward
VA-20027 Smyth
VA-20027 Washington
VA-20027 Wythe
VA-20027 Waynesboro
NE-20026 Garden
NE-20024 Arthur
NE-20024 Garden
NE-20024 Grant
NE-20024 Lincoln
NE-20024 Morrill
NE-20025 Garden
NE-20025 Grant
NE-20025 Lincoln
NE-20025 Morrill
ID-20035 Clearwater
ID-20035 Latah
ID-20035 Nez Perce
ID-20033 Benewah
ID-20033 Bonner
ID-20033 Clearwater
ID-20033 Kootenai
ID-20033 Latah
ID-20033 Nez Perce
TN-20035 Sullivan
IL-20024 Kankakee
HI-20014 Honolulu
HI-20014 Hawaii
HI-20014 Maui
HI-20010 Hawaii
HI-20010 Honolulu
HI-20010 Maui
IN-20019 Jasper
IN-20019 Newton
WA-20031 Okanogan
MI-20043 Branch
MI-20043 Cass
MI-20043 St. Joseph
TX-20082 Andrews
TX-20082 Armstrong
TX-20082 Carson
TX-20082 Dallam
TX-20082 Donley
TX-20082 Ector
TX-20082 Gray
TX-20082 Hansford
TX-20082 Haskell
TX-20082 Hemphill
TX-20082 Hill
TX-20082 Hutchinson
TX-20082 Lipscomb
TX-20082 Ochiltree
TX-20082 Potter
TX-20082 Randall
TX-20082 Roberts
TX-20082 Swisher
TX-20082 Wheeler
TX-20082 Moore
ID-20028 Owyhee
TX-20084 Archer
TX-20084 Kaufman
OK-20039 Nowata
OK-20039 Tulsa
AL-20015 Mobile
DE-20001 Kent
DE-20001 Sussex
MA-20004 Barnstable
MA-20004 Bristol
MA-20004 Dukes
MA-20004 Plymouth
MA-20005 Barnstable
RI-20005 Kent
RI-20005 Providence
PA-20028 Northampton
WY-20019 Big Horn
WY-20019 Fremont
WY-20019 Hot Springs
SC-20023 Marion
GA-20027 Bartow
GA-20027 Cherokee
GA-20027 Cobb
GA-20027 Douglas
GA-20027 Floyd
AL-20013 Cherokee
AL-20014 DeKalb
AL-20014 Jackson
GA-20026 Butts
GA-20026 Chattooga
GA-20026 Clayton
GA-20026 Coweta
GA-20026 Dade
GA-20026 Dawson
GA-20026 DeKalb
GA-20026 Fayette
GA-20026 Fulton
GA-20026 Gordon
GA-20026 Habersham
GA-20026 Henry
GA-20026 Jasper
GA-20026 Newton
GA-20026 Pickens
GA-20026 Pike
GA-20026 Putnam
GA-20026 Rabun
GA-20026 Rockdale
GA-20026 Spalding
SC-20022 Berkeley
SC-20022 Charleston
SC-20022 Georgetown
SC-20022 Horry
SC-20022 Williamsburg
OK-20035 Beaver
OK-20035 Bryan
OK-20035 Garfield
OK-20035 Harper
OK-20035 Logan
OK-20035 Love
OK-20035 McIntosh
OK-20035 Major
OK-20035 Murray
OK-20035 Noble
OK-20035 Okfuskee
OK-20035 Pawnee
OK-20035 Payne
OK-20035 Rogers
OK-20035 Texas
TX-20080 Briscoe
TX-20080 Childress
TX-20080 Clay
TX-20080 Cottle
TX-20080 Falls
TX-20080 Fisher
TX-20080 Freestone
TX-20080 Glasscock
TX-20080 Hale
TX-20080 Hardeman
TX-20080 Hall
TX-20080 Harrison
TX-20080 Henderson
TX-20080 Hockley
TX-20080 Howard
TX-20080 Jefferson
TX-20080 Kent
TX-20080 King
TX-20080 Knox
TX-20080 Lamb
TX-20080 Limestone
TX-20080 Martin
TX-20080 Midland
TX-20080 Mitchell
TX-20080 Navarro
TX-20080 Newton
TX-20080 Orange
TX-20080 Scurry
TX-20080 Smith
TX-20080 Stonewall
TX-20080 Van Zandt
TX-20080 Walker
TX-20080 Wichita
TX-20080 Yoakum
AR-20040 Lafayette
AR-20040 Logan
AR-20040 Madison
AR-20040 Miller
AR-20040 Nevada
CO-20028 Archuleta
CO-20028 Conejos
CO-20028 Custer
CO-20028 Dolores
CO-20028 Hinsdale
CO-20028 La Plata
CO-20028 Mineral
CO-20028 Montezuma
CO-20028 Phillips
CO-20028 Pueblo
CO-20028 Rio Grande
CO-20028 Saguache
CO-20028 San Juan
CO-20028 San Miguel
CO-20028 Teller
CO-20028 Yuma
LA-20016 Bossier
LA-20016 Caddo
LA-20016 Claiborne
LA-20016 Jefferson
LA-20016 Richland
LA-20016 St. Martin
LA-20016 Vernon
LA-20016 Webster
NY-20032 Suffolk
MS-20019 Adams
MS-20019 Alcorn
MS-20019 Attala
MS-20019 Benton
MS-20019 Bolivar
MS-20019 Calhoun
MS-20019 Carroll
MS-20019 Choctaw
MS-20019 Claiborne
MS-20019 Grenada
MS-20019 Holmes
MS-20019 Humphreys
MS-20019 Issaquena
MS-20019 Itawamba

## save each result into a list

In [37]:
rows = []

In [38]:
for disaster in data:
    
    for county in disaster["primary_counties"]:
        
        row = {
            "disaster_number": disaster["disaster_number"],
            "county_name": county["county_name"],
            "state": county["state"],
            "county_fips": county["fips_code_6"]
        }
        
        rows.append(row)

In [39]:
        len(rows)

2650

In [40]:
rows[:3]

[{'disaster_number': 'IN-20022',
  'county_name': 'Carroll',
  'state': 'IN',
  'county_fips': '18015'},
 {'disaster_number': 'IN-20022',
  'county_name': 'Dearborn',
  'state': 'IN',
  'county_fips': '18029'},
 {'disaster_number': 'IN-20022',
  'county_name': 'Decatur',
  'state': 'IN',
  'county_fips': '18031'}]

## Convert rows to a DataFrame

In [41]:
df = pd.DataFrame(rows)
df.head()

  disaster_number county_name state county_fips
0        IN-20022     Carroll    IN       18015
1        IN-20022    Dearborn    IN       18029
2        IN-20022     Decatur    IN       18031
3        IN-20022    Delaware    IN       18035
4        IN-20022     Fayette    IN       18041

In [42]:
df.shape

(2650, 4)

## To save as CSV

In [43]:
df.to_csv(r"Data/sba_primary_counties_test.csv", index=False)
print("CSV created successfully!")
print("Total rows:", len(df))
df

CSV created successfully!
Total rows: 2650

     disaster_number   county_name state county_fips
0           IN-20022       Carroll    IN       18015
1           IN-20022      Dearborn    IN       18029
2           IN-20022       Decatur    IN       18031
3           IN-20022      Delaware    IN       18035
4           IN-20022       Fayette    IN       18041
...              ...           ...   ...         ...
2645        AR-20032      Randolph    AR       05121
2646        NH-20012      Cheshire    NH       33005
2647        TX-20075  San Patricio    TX       48409
2648        MI-20040          Kent    MI       26081
2649        MI-20040       Midland    MI       26111

[2650 rows x 4 columns]

## add the Primary and  contiguous counties

In [44]:
rows = []

for disaster in data:

    for county in disaster["primary_counties"]:

        row = {
            "disaster_number": disaster["disaster_number"],
            "county_name": county["county_name"],
            "state": county["state"],
            "county_fips": county["fips_code_6"],
            "county_type": "Primary"
        }

        rows.append(row)


    for county in disaster["contiguous_counties"]:

        row = {
            "disaster_number": disaster["disaster_number"],
            "county_name": county["county_name"],
            "state": county["state"],
            "county_fips": county["fips_code_6"],
            "county_type": "Contiguous"
        }

        rows.append(row)

## convert to dataframe

In [45]:
df = pd.DataFrame(rows)

df["county_type"].value_counts()

county_type
Contiguous    4572
Primary       2650
Name: count, dtype: int64

In [46]:
len(df)

7222

In [47]:
df.shape

(7222, 5)

## Add the other important disaster fields
#disaster_description, incident_start_date, incident_end_date, declaration_date, status ,physical_deadline_date,eidl_deadline_date

In [48]:
rows = []

for disaster in data:

    # Primary counties
    for county in disaster["primary_counties"]:

        row = {
            "disaster_number": disaster["disaster_number"],
            "state": county["state"],
            "disaster_description": disaster["disaster_description"],
            "incident_start_date": disaster["incident_start_date"],
            "incident_end_date": disaster["incident_end_date"],
            "declaration_date": disaster["declaration_date"],
            "declaration_type": disaster["declaration_type_display"],
            "status": disaster["disaster_status_display"],
            "physical_deadline_date": disaster["physical_deadline_date"],
            "eidl_deadline_date": disaster["eidl_deadline_date"],
            "fema_number": disaster["fema_number"],
            "county_type": "Primary",
            "county_name": county["county_name"],
            "county_fips": county["fips_code_6"],
            "latitude": county.get("latitude", ""),
            "longitude": county.get("longitude", "")
        }

        rows.append(row)


    # Contiguous counties
    for county in disaster["contiguous_counties"]:

        row = {
            "disaster_number": disaster["disaster_number"],
            "state": county["state"],
            "disaster_description": disaster["disaster_description"],
            "incident_start_date": disaster["incident_start_date"],
            "incident_end_date": disaster["incident_end_date"],
            "declaration_date": disaster["declaration_date"],
            "declaration_type": disaster["declaration_type_display"],
            "status": disaster["disaster_status_display"],
            "physical_deadline_date": disaster["physical_deadline_date"],
            "eidl_deadline_date": disaster["eidl_deadline_date"],
            "fema_number": disaster["fema_number"],
            "county_type": "Contiguous",
            "county_name": county["county_name"],
            "county_fips": county["fips_code_6"],
            "latitude": county.get("latitude", ""),
            "longitude": county.get("longitude", "")
        }

        rows.append(row)

In [49]:
rows=[]
for disaster in data:
# Primary counties
    for county in disaster["primary_counties"]:
        row= {"disaster_number": disaster["disaster_number"],
            "state": county["state"],
            "disaster_description": disaster["disaster_description"],
            "incident_start_date": disaster["incident_start_date"],
            "incident_end_date": disaster["incident_end_date"],
            "declaration_date": disaster["declaration_date"],
            "declaration_type": disaster["declaration_type_display"],
            "status": disaster["disaster_status_display"],
            "physical_deadline_date": disaster["physical_deadline_date"],
            "eidl_deadline_date": disaster["eidl_deadline_date"],
            "fema_number": disaster["fema_number"],
            "county_type": "Primary",
            "county_name": county["county_name"],
            "county_fips": county["fips_code_6"],
            "latitude": county.get("latitude", ""),       ## some counties don't have latitude/longitude
            "longitude": county.get("longitude", "")}

        rows.append(row)


 # Contiguous counties
    for county in disaster["contiguous_counties"]:

        row = {"disaster_number": disaster["disaster_number"],
            "state": county["state"],
            "disaster_description": disaster["disaster_description"],
            "incident_start_date": disaster["incident_start_date"],
            "incident_end_date": disaster["incident_end_date"],
            "declaration_date": disaster["declaration_date"],
            "declaration_type": disaster["declaration_type_display"],
            "status": disaster["disaster_status_display"],
            "physical_deadline_date": disaster["physical_deadline_date"],
            "eidl_deadline_date": disaster["eidl_deadline_date"],
            "fema_number": disaster["fema_number"],
            "county_type": "Contiguous",
            "county_name": county["county_name"],
            "county_fips": county["fips_code_6"],
            "latitude": county.get("latitude", ""),
            "longitude": county.get("longitude", "")}

        rows.append(row)

## data frame

In [50]:
df = pd.DataFrame(rows)
df.head()

,disaster_number,state,disaster_description,incident_start_date,incident_end_date,declaration_date,declaration_type,status,physical_deadline_date,eidl_deadline_date,fema_number,county_type,county_name,county_fips,latitude,longitude
0,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Carroll,18015,40.58498,-86.565141
1,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Dearborn,18029,39.140897,-84.975868
2,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Decatur,18031,39.30598,-85.499831
3,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Delaware,18035,40.227543,-85.399262
4,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Fayette,18041,39.639655,-85.185032

In [51]:
df.shape

(7222, 16)

In [52]:
df["county_type"].value_counts()

county_type
Contiguous    4572
Primary       2650
Name: count, dtype: int64

## check the missing latitude/longitude

In [53]:
df[["latitude", "longitude"]].isna().sum()

latitude     29
longitude    29
dtype: int64

In [54]:
df[df["latitude"].isna()|df["longitude"].isna()]["county_type"].value_counts()

county_type
Primary    29
Name: count, dtype: int64

In [55]:
df[df["latitude"].isna()][
    ["state", "county_name", "county_fips", "county_type"]
].head(20)

     state                     county_name county_fips county_type
115     MP                            Rota       69100     Primary
116     MP                          Saipan       69110     Primary
117     MP                          Tinian       69120     Primary
127     MP                            Rota       69100     Primary
145     VI                     SAINT CROIX       78010     Primary
146     VI                      SAINT JOHN       78020     Primary
147     VI                    SAINT THOMAS       78030     Primary
1445    SD                   Oglala Lakota       46102     Primary
1889    GU                            GUAM       66010     Primary
1890    MP   Northern Islands Municipality       69085     Primary
1891    MP               Rota Municipality       69100     Primary
1892    MP             Saipan Municipality       69110     Primary
1893    MP             Tinian Municipality       69120     Primary
1894    MP   Northern Islands Municipality       69085     Primary
1895    MP               Rota Municipality       69100     Primary
1896    MP             Saipan Municipality       69110     Primary
1897    MP             Tinian Municipality       69120     Primary
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272     Primary
5889    AK       LOWER KUSKOKWIM REAA (31)       02053     Primary
5890    AK           LOWER YUKON REAA (32)       02271     Primary

## To identify exactly which counties have missing coordinates

In [56]:
missing_coordinates = df[ df["latitude"].isna()| df["longitude"].isna()]

## to display

In [57]:
missing_coordinates[
    ["state", "county_name", "county_fips", "county_type"]]

     state                     county_name county_fips county_type
115     MP                            Rota       69100     Primary
116     MP                          Saipan       69110     Primary
117     MP                          Tinian       69120     Primary
127     MP                            Rota       69100     Primary
145     VI                     SAINT CROIX       78010     Primary
146     VI                      SAINT JOHN       78020     Primary
147     VI                    SAINT THOMAS       78030     Primary
1445    SD                   Oglala Lakota       46102     Primary
1889    GU                            GUAM       66010     Primary
1890    MP   Northern Islands Municipality       69085     Primary
1891    MP               Rota Municipality       69100     Primary
1892    MP             Saipan Municipality       69110     Primary
1893    MP             Tinian Municipality       69120     Primary
1894    MP   Northern Islands Municipality       69085     Primary
1895    MP               Rota Municipality       69100     Primary
1896    MP             Saipan Municipality       69110     Primary
1897    MP             Tinian Municipality       69120     Primary
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272     Primary
5889    AK       LOWER KUSKOKWIM REAA (31)       02053     Primary
5890    AK           LOWER YUKON REAA (32)       02271     Primary
5892    AK                YUPIIT REAA (54)       02051     Primary
5900    AK         IDITAROD AREA REAA (21)       02291     Primary
5901    AK  KASHUNAMIUT (Chevak) REAA (55)       02272     Primary
5902    AK       LOWER KUSKOKWIM REAA (31)       02053     Primary
5903    AK           LOWER YUKON REAA (32)       02271     Primary
5905    AK      PRIBILOF ISLANDS REAA (40)       02018     Primary
5906    AK                YUPIIT REAA (54)       02051     Primary
5907    AK                   Yukon-Koyukuk       02290     Primary
5908    AK       LOWER KUSKOKWIM REAA (31)       02053     Primary

In [58]:
len(missing_coordinates)

29

## Show unique counties only

In [59]:
unique_missing = missing_coordinates[
    ["state", "county_name", "county_fips"]
].drop_duplicates()

unique_missing

     state                     county_name county_fips
115     MP                            Rota       69100
116     MP                          Saipan       69110
117     MP                          Tinian       69120
145     VI                     SAINT CROIX       78010
146     VI                      SAINT JOHN       78020
147     VI                    SAINT THOMAS       78030
1445    SD                   Oglala Lakota       46102
1889    GU                            GUAM       66010
1890    MP   Northern Islands Municipality       69085
1891    MP               Rota Municipality       69100
1892    MP             Saipan Municipality       69110
1893    MP             Tinian Municipality       69120
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

In [60]:
unique_missing = missing_coordinates[["state", "county_name", "county_fips"]].drop_duplicates()
unique_missing

     state                     county_name county_fips
115     MP                            Rota       69100
116     MP                          Saipan       69110
117     MP                          Tinian       69120
145     VI                     SAINT CROIX       78010
146     VI                      SAINT JOHN       78020
147     VI                    SAINT THOMAS       78030
1445    SD                   Oglala Lakota       46102
1889    GU                            GUAM       66010
1890    MP   Northern Islands Municipality       69085
1891    MP               Rota Municipality       69100
1892    MP             Saipan Municipality       69110
1893    MP             Tinian Municipality       69120
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

In [61]:
len(unique_missing)

19

In [62]:
unique_missing

     state                     county_name county_fips
115     MP                            Rota       69100
116     MP                          Saipan       69110
117     MP                          Tinian       69120
145     VI                     SAINT CROIX       78010
146     VI                      SAINT JOHN       78020
147     VI                    SAINT THOMAS       78030
1445    SD                   Oglala Lakota       46102
1889    GU                            GUAM       66010
1890    MP   Northern Islands Municipality       69085
1891    MP               Rota Municipality       69100
1892    MP             Saipan Municipality       69110
1893    MP             Tinian Municipality       69120
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

## how the 29 records are distributed among those places:

In [63]:
missing_coordinates[["state", "county_name", "county_fips"]].value_counts()

state  county_name                     county_fips
AK     LOWER KUSKOKWIM REAA (31)       02053          3
MP     Rota                            69100          2
AK     LOWER YUKON REAA (32)           02271          2
       YUPIIT REAA (54)                02051          2
MP     Northern Islands Municipality   69085          2
AK     KASHUNAMIUT (Chevak) REAA (55)  02272          2
MP     Rota Municipality               69100          2
       Tinian Municipality             69120          2
       Saipan Municipality             69110          2
       Tinian                          69120          1
VI     SAINT JOHN                      78020          1
       SAINT CROIX                     78010          1
SD     Oglala Lakota                   46102          1
AK     IDITAROD AREA REAA (21)         02291          1
MP     Saipan                          69110          1
GU     GUAM                            66010          1
AK     Yukon-Koyukuk                   02290          1
       PRIBILOF ISLANDS REAA (40)      02018          1
VI     SAINT THOMAS                    78030          1
Name: count, dtype: int64

## count unique FIPS

In [64]:
missing_coordinates["county_fips"].nunique()

16

## count the actual unique FIPS

In [65]:
missing_coordinates[["state", "county_name", "county_fips"]].value_counts()

state  county_name                     county_fips
AK     LOWER KUSKOKWIM REAA (31)       02053          3
MP     Rota                            69100          2
AK     LOWER YUKON REAA (32)           02271          2
       YUPIIT REAA (54)                02051          2
MP     Northern Islands Municipality   69085          2
AK     KASHUNAMIUT (Chevak) REAA (55)  02272          2
MP     Rota Municipality               69100          2
       Tinian Municipality             69120          2
       Saipan Municipality             69110          2
       Tinian                          69120          1
VI     SAINT JOHN                      78020          1
       SAINT CROIX                     78010          1
SD     Oglala Lakota                   46102          1
AK     IDITAROD AREA REAA (21)         02291          1
MP     Saipan                          69110          1
GU     GUAM                            66010          1
AK     Yukon-Koyukuk                   02290          1
       PRIBILOF ISLANDS REAA (40)      02018          1
VI     SAINT THOMAS                    78030          1
Name: count, dtype: int64

In [66]:
missing_fips = missing_coordinates[["state", "county_name", "county_fips"]].drop_duplicates(subset=["county_fips"])

print("Unique FIPS missing coordinates:", len(missing_fips))

missing_fips

Unique FIPS missing coordinates: 16

     state                     county_name county_fips
115     MP                            Rota       69100
116     MP                          Saipan       69110
117     MP                          Tinian       69120
145     VI                     SAINT CROIX       78010
146     VI                      SAINT JOHN       78020
147     VI                    SAINT THOMAS       78030
1445    SD                   Oglala Lakota       46102
1889    GU                            GUAM       66010
1890    MP   Northern Islands Municipality       69085
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

## separate missing FIPS by state

In [67]:
missing_fips["state"].value_counts()

state
AK    7
MP    4
VI    3
SD    1
GU    1
Name: count, dtype: int64

In [68]:
missing_fips.sort_values(["state", "county_fips"])

     state                     county_name county_fips
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5892    AK                YUPIIT REAA (54)       02051
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5907    AK                   Yukon-Koyukuk       02290
5900    AK         IDITAROD AREA REAA (21)       02291
1889    GU                            GUAM       66010
1890    MP   Northern Islands Municipality       69085
115     MP                            Rota       69100
116     MP                          Saipan       69110
117     MP                          Tinian       69120
1445    SD                   Oglala Lakota       46102
145     VI                     SAINT CROIX       78010
146     VI                      SAINT JOHN       78020
147     VI                    SAINT THOMAS       78030

## start with Alaska and South Dakota

In [69]:
missing_us = missing_fips[missing_fips["state"].isin(["AK", "SD"])].copy()

missing_us

     state                     county_name county_fips
1445    SD                   Oglala Lakota       46102
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

## to make sure FIPS stays as text

In [70]:
missing_us["county_fips"] =(missing_us["county_fips"].astype(str).str.zfill(5))
#county FIPS -- convert to text -- make it 5 characters long by adding leading zeros.

missing_us

     state                     county_name county_fips
1445    SD                   Oglala Lakota       46102
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272
5889    AK       LOWER KUSKOKWIM REAA (31)       02053
5890    AK           LOWER YUKON REAA (32)       02271
5892    AK                YUPIIT REAA (54)       02051
5900    AK         IDITAROD AREA REAA (21)       02291
5905    AK      PRIBILOF ISLANDS REAA (40)       02018
5907    AK                   Yukon-Koyukuk       02290

## create FIPS + latitude + longitude.

# Download the Census county Gazetteer file and read it in Jupyter...USING 2025 CENSUS DATA
#https://www.census.gov/geographies/reference-files/time-series/geo/gazetteer-files.2025.html#list-tab-264479560
#to get the lat long

In [71]:
county_ref = pd.read_csv(
    "Data/2025_Gaz_elsd_national.txt",
    sep="\t",
    dtype={"GEOID": str}
)

county_ref.head()

  USPS|GEOID|GEOIDFQ|NAME|LOGRADE|HIGRADE|ALAND|AWATER|ALAND_SQMI|AWATER_SQMI|INTPTLAT|INTPTLONG
0  AZ|0400004|9500000US0400004|Clarkdale-Jerome E...
1  AZ|0400005|9500000US0400005|Salome Consolidate...
2  AZ|0400022|9500000US0400022|Vernon Elementary ...
3  AZ|0400480|9500000US0400480|Aguila Elementary ...
4  AZ|0400600|9500000US0400600|Alhambra Elementar...

In [72]:
county_ref = pd.read_csv(r"Data/2025_Gaz_counties_national.txt", sep = "|", dtype={"GEOID": str}    
)            
county_ref.head()                     #"|" Census file is tab-separated, rather than comma-separated

,USPS,GEOID,GEOIDFQ,ANSICODE,NAME,ALAND,AWATER,ALAND_SQMI,AWATER_SQMI,INTPTLAT,INTPTLONG
0,AL,01001,0500000US01001,161526,Autauga County,1539631460,25677536,594.455,9.914,32.532237,-86.646440
1,AL,01003,0500000US01003,161527,Baldwin County,4117933903,1132678359,1589.943,437.330,30.659218,-87.746067
2,AL,01005,0500000US01005,161528,Barbour County,2292160152,50523213,885.008,19.507,31.870253,-85.405103
3,AL,01007,0500000US01007,161529,Bibb County,1612188713,9572302,622.470,3.696,33.015893,-87.127148
4,AL,01009,0500000US01009,161530,Blount County,1670296790,14822589,644.905,5.723,33.977358,-86.566440

## check if 8 missing FIPS exist in this Census file

In [73]:
county_match = county_ref[
    county_ref["GEOID"].isin(missing_us["county_fips"])
]

county_match[
    ["USPS", "GEOID", "NAME", "INTPTLAT", "INTPTLONG"]
]

     USPS  GEOID                       NAME   INTPTLAT   INTPTLONG
96     AK  02290  Yukon-Koyukuk Census Area  65.375656 -151.578176
2414   SD  46102       Oglala Lakota County  43.333393 -102.561486

In [74]:
county_match = county_ref[
    county_ref["GEOID"].isin(missing_us["county_fips"])
]

county_match[
    ["USPS", "GEOID", "NAME", "INTPTLAT", "INTPTLONG"]
]

     USPS  GEOID                       NAME   INTPTLAT   INTPTLONG
96     AK  02290  Yukon-Koyukuk Census Area  65.375656 -151.578176
2414   SD  46102       Oglala Lakota County  43.333393 -102.561486

## 6 unusual Alaska REAA records
#From TIGER line/ census---- downloaded the alaska ununified school distric shp file--and read the file

In [75]:
school = gpd.read_file(r"Data/tl_2025_02_unsd.zip")
school.head()

,STATEFP,UNSDLEA,GEOID,GEOIDFQ,NAME,LSAD,LOGRADE,HIGRADE,MTFCC,SDTYP,FUNCSTAT,ALAND,AWATER,INTPTLAT,INTPTLON,geometry
0,02,00001,0200001,9700000US0200001,Lower Kuskokwim School District,00,PK,12,G5420,None,E,55256506515,12814014185,+60.2134905,-163.4359235,"MULTIPOLYGON (((-165.94413 61.28196, -165.9069..."
1,02,00003,0200003,9700000US0200003,Lower Yukon School District,00,PK,12,G5420,None,E,45797172054,5640643119,+62.2835555,-163.1901536,"POLYGON ((-166.28643 61.6031, -166.27993 61.62..."
2,02,00004,0200004,9700000US0200004,Yupiit School District,00,KG,12,G5420,None,E,35510236,7707312,+60.9097122,-161.4073619,"MULTIPOLYGON (((-160.98419 61.11599, -160.9840..."
3,02,00005,0200005,9700000US0200005,Kashunamiut School District,00,PK,12,G5420,None,E,2827582,132641,+61.5295354,-165.5942167,"POLYGON ((-165.611 61.52334, -165.61099 61.525..."
4,02,00007,0200007,9700000US0200007,Aleutians East Borough School District,00,PK,12,G5420,None,E,18092037389,20799701286,+55.2450437,-161.9974772,"MULTIPOLYGON (((-159.91034 54.81417, -159.9057..."

In [76]:
school.columns

Index(['STATEFP', 'UNSDLEA', 'GEOID', 'GEOIDFQ', 'NAME', 'LSAD', 'LOGRADE',
       'HIGRADE', 'MTFCC', 'SDTYP', 'FUNCSTAT', 'ALAND', 'AWATER', 'INTPTLAT',
       'INTPTLON', 'geometry'],
      dtype='object')

## check whether the six Alaska REAA names are present in this school-district file.

In [77]:
school[
    school["NAME"].str.contains("Kuskokwim|Iditarod|Kashunamiut|Lower Yukon|Pribilof|Yupiit",
        case=False,
        na=False
    )
][["NAME", "GEOID", "INTPTLAT", "INTPTLON"]]

                               NAME    GEOID     INTPTLAT      INTPTLON
0   Lower Kuskokwim School District  0200001  +60.2134905  -163.4359235
1       Lower Yukon School District  0200003  +62.2835555  -163.1901536
2            Yupiit School District  0200004  +60.9097122  -161.4073619
3       Kashunamiut School District  0200005  +61.5295354  -165.5942167
28    Iditarod Area School District  0200520  +62.7048922  -156.1553811
37         Pribilof School District  0200670  +57.0495083  -170.4062251

## lookup table manually from the Census results

In [78]:
reaa_lookup = {"02053":(60.2134905, -163.4359235),
               "02291": (62.7048922, -156.1553811),
               "02272": (61.5295354, -165.5942167),
               "02271": (62.2835555, -163.1901536),
               "02018": (57.0495083, -170.4062251),
               "02051": (60.9097122, -161.4073619)}

In [79]:
reaa_lookup

{'02053': (60.2134905, -163.4359235),
 '02291': (62.7048922, -156.1553811),
 '02272': (61.5295354, -165.5942167),
 '02271': (62.2835555, -163.1901536),
 '02018': (57.0495083, -170.4062251),
 '02051': (60.9097122, -161.4073619)}

## 1st create a copy of data

In [80]:
df_test = df.copy()

## to make sure FIPS is text

In [81]:
df_test["county_fips"] = (
    df_test["county_fips"]
    .astype(str)
    .str.zfill(5)
)

In [82]:
df_test["county_fips"] = ( df_test["county_fips"].astype(str).str.zfill(5))

## run the filling loop on the df_test copy:

In [83]:
for fips, coordinates in reaa_lookup.items():

    latitude = coordinates[0]
    longitude = coordinates[1]

    mask = (
        (df_test["county_fips"] == fips) &
        (df_test["latitude"].isna())
    )

    df_test.loc[mask, "latitude"] = latitude
    df_test.loc[mask, "longitude"] = longitude

In [84]:
for fips, coordinates in reaa_lookup.items():

    latitude = coordinates[0]
    longitude = coordinates[1]

    mask = (
        (df_test["county_fips"] == fips) &
        (df_test["latitude"].isna())
    )

    df_test.loc[mask, "latitude"] = latitude
    df_test.loc[mask, "longitude"] = longitude

## check if REAA rows now have coordinates

In [85]:
df_test[df_test["county_fips"].isin(reaa_lookup.keys())][
    ["state", "county_name", "county_fips", "latitude", "longitude"]
]

     state                     county_name county_fips   latitude   longitude
5888    AK  KASHUNAMIUT (Chevak) REAA (55)       02272  61.529535 -165.594217
5889    AK       LOWER KUSKOKWIM REAA (31)       02053   60.21349 -163.435924
5890    AK           LOWER YUKON REAA (32)       02271  62.283555 -163.190154
5892    AK                YUPIIT REAA (54)       02051  60.909712 -161.407362
5894    AK         IDITAROD AREA REAA (21)       02291
5900    AK         IDITAROD AREA REAA (21)       02291  62.704892 -156.155381
5901    AK  KASHUNAMIUT (Chevak) REAA (55)       02272  61.529535 -165.594217
5902    AK       LOWER KUSKOKWIM REAA (31)       02053   60.21349 -163.435924
5903    AK           LOWER YUKON REAA (32)       02271  62.283555 -163.190154
5905    AK      PRIBILOF ISLANDS REAA (40)       02018  57.049508 -170.406225
5906    AK                YUPIIT REAA (54)       02051  60.909712 -161.407362
5908    AK       LOWER KUSKOKWIM REAA (31)       02053   60.21349 -163.435924

In [86]:
df_test.loc[5903, [
    "county_name",
    "county_fips",
    "latitude",
    "longitude"
]]

county_name    LOWER YUKON REAA (32)
county_fips                    02271
latitude                   62.283555
longitude                -163.190154
Name: 5903, dtype: object

In [87]:
import pandas as pd

df_test["latitude"] = df_test["latitude"].replace("", pd.NA)
df_test["longitude"] = df_test["longitude"].replace("", pd.NA)

In [88]:
df_test.loc[5903, [
    "county_name",
    "county_fips",
    "latitude",
    "longitude"
]]

county_name    LOWER YUKON REAA (32)
county_fips                    02271
latitude                   62.283555
longitude                -163.190154
Name: 5903, dtype: object

In [89]:
for fips, coordinates in reaa_lookup.items():

    latitude = coordinates[0]
    longitude = coordinates[1]

    mask = (
        (df_test["county_fips"] == fips) &
        (df_test["latitude"].isna())
    )

    df_test.loc[mask, "latitude"] = latitude
    df_test.loc[mask, "longitude"] = longitude

In [90]:
df_test.loc[5903, [
    "county_name",
    "county_fips",
    "latitude",
    "longitude"
]]

county_name    LOWER YUKON REAA (32)
county_fips                    02271
latitude                   62.283555
longitude                -163.190154
Name: 5903, dtype: object

In [91]:
for fips, coordinates in reaa_lookup.items():

    latitude = coordinates[0]
    longitude = coordinates[1]

    mask = (
        (df_test["county_fips"] == fips) &
        (df_test["latitude"].isna())
    )

    df_test.loc[mask, "latitude"] = latitude
    df_test.loc[mask, "longitude"] = longitude

In [92]:
print("Missing latitude:", df_test["latitude"].isna().sum())
print("Missing longitude:", df_test["longitude"].isna().sum())

Missing latitude: 4589
Missing longitude: 4589

In [93]:
df_test[
    df_test["latitude"].isna()
]["county_type"].value_counts()

county_type
Contiguous    4571
Primary         18
Name: count, dtype: int64

In [94]:
print("Total rows:", len(df_test))
print("Missing coordinates:", df_test["latitude"].isna().sum())
print("Coordinates available:", df_test["latitude"].notna().sum())

Total rows: 7222
Missing coordinates: 4589
Coordinates available: 2633

## find how many unique FIPS codes are missing.

In [95]:
missing_all = df_test[df_test["latitude"].isna()].copy()

In [96]:
print("missing rows:", len(missing_all))
print("unique FIPS with missing coordinates:",
      missing_all["county_fips"].nunique())

missing rows: 4589
unique FIPS with missing coordinates: 2212

## check by county type

In [97]:
print(
    "Unique missing Primary FIPS:",
    missing_all[
        missing_all["county_type"] == "Primary"
    ]["county_fips"].nunique()
)

print(
    "Unique missing Contiguous FIPS:",
    missing_all[
        missing_all["county_type"] == "Contiguous"
    ]["county_fips"].nunique()
)

Unique missing Primary FIPS: 10
Unique missing Contiguous FIPS: 2205

## test all missing FIPS against Census

In [98]:
missing_match = county_ref[
    county_ref["GEOID"].isin(missing_all["county_fips"])
]

print("Unique missing FIPS:", missing_all["county_fips"].nunique())
print("Found in Census:", missing_match["GEOID"].nunique())

Unique missing FIPS: 2212
Found in Census: 2195

In [99]:
missing_match = county_ref[county_ref["GEOID"].isin(missing_all["county_fips"])]

print("unique missing FIPS:", missing_match["GEOID"].nunique())
print("found in census:", missing_match["GEOID"].nunique())

unique missing FIPS: 2195
found in census: 2195

## merge the Census coordinates into df_test

## create a small Census lookup:

In [100]:
census_lookup = county_ref[["GEOID", "INTPTLAT", "INTPTLONG"]].copy()

## merge it with df_test:

In [101]:
df_test = df_test.merge(census_lookup,
                        left_on = "county_fips",
                        right_on ="GEOID",
                        how= "left")

In [102]:
df_test

,disaster_number,state,disaster_description,incident_start_date,incident_end_date,declaration_date,declaration_type,status,physical_deadline_date,eidl_deadline_date,fema_number,county_type,county_name,county_fips,latitude,longitude,GEOID,INTPTLAT,INTPTLONG
0,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Carroll,18015,40.58498,-86.565141,18015,40.584980,-86.565141
1,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Dearborn,18029,39.140897,-84.975868,18029,39.140897,-84.975868
2,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Decatur,18031,39.30598,-85.499831,18031,39.305980,-85.499831
3,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Delaware,18035,40.227543,-85.399262,18035,40.227543,-85.399262
4,IN-20022,IN,"Severe Storms, Straight-line Winds, Tornadoes,...",2026-08-11,None,2026-08-25,Presidential-Individual Assistance,Disaster Declared,2026-10-25,2027-05-25,4933,Primary,Fayette,18041,39.639655,-85.185032,18041,39.639654,-85.185034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7217,MI-20040,MI,Drought,2024-12-03,2025-12-31,2026-02-13,Secretary of Agriculture,Disaster Declared,None,2026-10-13,,Contiguous,Muskegon,26121,<NA>,<NA>,26121,43.428739,-86.420908
7218,MI-20040,MI,Drought,2024-12-03,2025-12-31,2026-02-13,Secretary of Agriculture,Disaster Declared,None,2026-10-13,,Contiguous,Newaygo,26123,<NA>,<NA>,26123,43.562712,-85.791372
7219,MI-20040,MI,Drought,2024-12-03,2025-12-31,2026-02-13,Secretary of Agriculture,Disaster Declared,None,2026-10-13,,Contiguous,Ottawa,26139,<NA>,<NA>,26139,43.054969,-86.219349
7220,MI-20040,MI,Drought,2024-12-03,2025-12-31,2026-02-13,Secretary of Agriculture,Disaster Declared,None,2026-10-13,,Contiguous,Saginaw,26145,<NA>,<NA>,26145,43.328267,-84.055410
7221,MI-20040,MI,Drought,2024-12-03,2025-12-31,2026-02-13,Secretary of Agriculture,Disaster Declared,None,2026-10-13,,Contiguous,Clare,26035,<NA>,<NA>,26035,43.991137,-84.838325

In [103]:
df_test[["county_fips", "latitude", "longitude", "INTPTLAT_x", "INTPTLONG_x"]].head()

KeyError: "['INTPTLAT_x', 'INTPTLONG_x'] not in index"

## fill the missing coordinates using the Census columns just joined
#.fillna If this value is missing, fill it using another value.

In [ ]:
df_test["latitude"] = pd.to_numeric(df_test["latitude"],errors="coerce") #something cannot be converted to a number, turn it into NaN

df_test["longitude"] = pd.to_numeric(df_test["longitude"],errors="coerce")

In [ ]:
df_test["latitude"] = df_test["latitude"].fillna(df_test["INTPTLAT_x"])

df_test["longitude"] = df_test["longitude"].fillna(df_test["INTPTLONG_y"])

In [ ]:
print("Missing latitude:", df_test["latitude"].isna().sum())
print("Missing longitude:", df_test["longitude"].isna().sum())

## find missing 31 rows

In [ ]:
missing_coordinates = df_test[df_test["latitude"].isna()].copy()
missing_coordinates["state"].value_counts()

In [ ]:
missing_coordinates[["state", "county_name", "county_fips", "county_type"]
].drop_duplicates()

In [ ]:
len(missing_coordinates)

In [ ]:
alaska_missing = missing_coordinates[missing_coordinates["state"] == "AK"]

alaska_missing[["county_name", "county_fips", "county_type"]
].drop_duplicates()

## find the two Alaska places inside the school GeoDataFrame

In [ ]:
school[school["NAME"].str.contains("Kuspuk|Yukon-Koyukuk", case=False, na=False)
][["NAME", "GEOID", "INTPTLAT", "INTPTLON"]]

## South Dakota record

In [ ]:
county_ref[county_ref["NAME"].str.contains(
        "Oglala",
        case=False,
        na=False
    )
][["USPS", "GEOID", "NAME", "INTPTLAT", "INTPTLONG"]]

In [ ]:
print("Missing rows:", len(missing_coordinates))

print("Unique FIPS:",missing_coordinates["county_fips"].nunique())

In [ ]:
missing_fips_17 = missing_coordinates[["state", "county_name", "county_fips"]
].drop_duplicates(subset=["county_fips"])

missing_fips_17

## to check if 17 are actually present in Census reference under a different name/code

In [ ]:
for fips in missing_fips_17["county_fips"]:

    match = county_ref[
        county_ref["GEOID"] == fips
    ]

    if len(match) > 0:
        print(fips, "FOUND")
    else:
        print(fips, "NOT FOUND")

In [ ]:
county_2021 = pd.read_csv(
    r"Data/2021_Gaz_counties_national.txt",
    sep="\t",
    dtype={"GEOID": str}
  
)
county_2021.head()

In [ ]:
county_2021.columns

In [ ]:
len(county_2021)

In [ ]:
county_2021.columns = county_2021.columns.str.strip()

In [ ]:
county_2021.columns

## check 17 missing fips

In [ ]:
match_2021 = county_2021[county_2021["GEOID"].isin(missing_fips_17["county_fips"])
]

match_2021[
    ["USPS", "GEOID", "NAME", "INTPTLAT", "INTPTLONG"]
]

In [ ]:
still_missing = missing_fips_17[
    ~missing_fips_17["county_fips"].isin(
        match_2021["GEOID"]
    )
]

still_missing

## create one combined lookup table for those 6 first:

In [ ]:
ct_lookup = match_2021[
    ["GEOID", "INTPTLAT", "INTPTLONG"]].copy()

ct_lookup

## rename the colum

In [ ]:
ct_lookup = ct_lookup.rename(
    columns={
        "GEOID": "county_fips",
        "INTPTLAT": "new_latitude",
        "INTPTLONG": "new_longitude"
    }
)

ct_lookup

In [ ]:
coordinate_lookup = ct_lookup.copy()

In [ ]:
ak_lookup = pd.DataFrame({
    "county_fips": ["02052", "02293"],
    "new_latitude": [61.5235547, 65.6344779],
    "new_longitude": [-158.0361130, -154.3251960]
})

In [ ]:
coordinate_lookup

In [ ]:
len(coordinate_lookup)

In [ ]:
ak_lookup = pd.DataFrame({
    "county_fips": ["02052", "02293"],
    "new_latitude": [61.5235547, 65.6344779],
    "new_longitude": [-158.0361130, -154.3251960]
})

## combine them

In [ ]:
coordinate_lookup = pd.concat(
    [coordinate_lookup, ak_lookup],
    ignore_index=True
)

In [ ]:
len(coordinate_lookup)

## all states missing

In [ ]:
import geopandas as gpd
import zipfile

zip_path = r"Data/tl_2021_us_county.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    print(z.namelist())

In [ ]:
county_shape_2021 = gpd.read_file(r"Data/tl_2021_us_county.zip")
county_shape_2021.head()

## test all 11 remaining FIPS at once

In [ ]:
county_shape_2021["GEOID"] = county_shape_2021["GEOID"].astype(str)

In [ ]:
match_shape_2021 = county_shape_2021[
    county_shape_2021["GEOID"].isin(
        still_missing["county_fips"]
    )
]

match_shape_2021[
    ["GEOID", "NAME", "INTPTLAT", "INTPTLON"]
]

## Oglala Lakota under another FIPS

In [ ]:
county_shape_2021[
    county_shape_2021["NAME"].str.contains(
        "Oglala",
        case=False,
        na=False
    )
][["GEOID", "NAME", "INTPTLAT", "INTPTLON"]]

In [ ]:
sd_lookup = pd.DataFrame({
    "county_fips": ["46113"],
    "new_latitude": [43.3333930],
    "new_longitude": [-102.5614857]
})

## 6 Connecticut + 2 Alaska + 8 Island Areas + 1 South Dakota into one lookup and fill all missing rows at once.

In [ ]:
# 1. 6 Connecticut rows
coordinate_lookup = ct_lookup.copy()

# 2. Add Alaska
ak_lookup = pd.DataFrame({
    "county_fips": ["02052", "02293"],
    "new_latitude": [61.5235547, 65.6344779],
    "new_longitude": [-158.0361130, -154.3251960]
})

coordinate_lookup = pd.concat(
    [coordinate_lookup, ak_lookup],
    ignore_index=True
)

# 3.Island Areas from the 2021 county shapefile
island_lookup = match_shape_2021[
    ["GEOID", "INTPTLAT", "INTPTLON"]
].copy()

island_lookup = island_lookup.rename(
    columns={
        "GEOID": "county_fips",
        "INTPTLAT": "new_latitude",
        "INTPTLON": "new_longitude"
    }
)

coordinate_lookup = pd.concat(
    [coordinate_lookup, island_lookup],
    ignore_index=True
)

# 4. South Dakota
sd_lookup = pd.DataFrame({
    "county_fips": ["46113"],
    "new_latitude": [43.3333930],
    "new_longitude": [-102.5614857]
})

coordinate_lookup = pd.concat(
    [coordinate_lookup, sd_lookup],
    ignore_index=True
)

In [ ]:
print("Lookup rows:", len(coordinate_lookup))
print("Unique FIPS:", coordinate_lookup["county_fips"].nunique())

## fill the missing coordinates in df_test:

In [ ]:
df_test = df_test.merge(
    coordinate_lookup,
    on="county_fips",
    how="left"
)

In [ ]:
df_test["latitude"] = df_test["latitude"].fillna(
    df_test["new_latitude"]
)

df_test["longitude"] = df_test["longitude"].fillna(
    df_test["new_longitude"]
)

In [ ]:
print("Missing latitude:", df_test["latitude"].isna().sum())
print("Missing longitude:", df_test["longitude"].isna().sum())

## 31 rows fixing

In [ ]:
df_test[
    df_test["county_fips"].isin(
        missing_fips_17["county_fips"]
    )
][
    ["state", "county_name", "county_fips", "latitude", "longitude"]
].drop_duplicates()

In [ ]:
print(df_test.columns.tolist())

## remove extra columns

In [ ]:
helper_columns = [
    "GEOID_x",
    "INTPTLAT_x",
    "INTPTLONG_x",
    "GEOID_y",
    "INTPTLAT_y",
    "INTPTLONG_y",
    "new_latitude",
    "new_longitude"
]

df_test = df_test.drop(
    columns=helper_columns,
    errors="ignore"
)

In [ ]:
print(df_test.columns.tolist())

In [ ]:
print("Rows:", len(df_test))
print("Missing latitude:", df_test["latitude"].isna().sum())
print("Missing longitude:", df_test["longitude"].isna().sum())

## final check

In [ ]:
print("Rows:", len(df_test))
print("Columns:", len(df_test.columns))
print("Unique disasters:", df_test["disaster_number"].nunique())
print("Unique counties:", df_test["county_fips"].nunique())

print("\nCounty types:")
print(df_test["county_type"].value_counts())

print("\nMissing coordinates:")
print(df_test[["latitude", "longitude"]].isna().sum())

## duplicate check

In [ ]:
duplicates = df_test.duplicated(
    subset=[
        "disaster_number",
        "county_fips",
        "county_type"
    ]
)

print("Duplicate rows:", duplicates.sum())

## final CSV saving

In [ ]:
df_test.to_csv(r"Data/SBA_disaster_Final.csv",
    index=False
)

print("Clean CSV saved.")
print("Total rows:", len(df_test))

## create map

In [ ]:
m = folium.Map(
    #location=[39.5, -98.35],
    location=[31.0, -99.0],
    zoom_start=5
    
)

m

## texas sba

In [108]:
import pandas as pd

dashboard_df = pd.read_csv(
    r"Data/SBA_disaster_Final.csv",
    dtype={"county_fips": str}
)

print("All rows:", len(dashboard_df))
print("Missing latitude:", dashboard_df["latitude"].isna().sum())
print("Missing longitude:", dashboard_df["longitude"].isna().sum())

All rows: 7232
Missing latitude: 0
Missing longitude: 0

## create the Texas subset

In [109]:
import pandas as pd

dashboard_df = pd.read_csv(
    r"Data/SBA_disaster_Final.csv",
    dtype={"county_fips": str}
)

texas_sba = dashboard_df[
    dashboard_df["state"] == "TX"
].copy()

print("Texas rows:", len(texas_sba))
print("Texas disasters:", texas_sba["disaster_number"].nunique())
print("Missing Texas latitude:", texas_sba["latitude"].isna().sum())
print("Missing Texas longitude:", texas_sba["longitude"].isna().sum())

Texas rows: 575
Texas disasters: 34
Missing Texas latitude: 0
Missing Texas longitude: 0

## create the map and add the Texas locations

In [120]:
from folium.plugins import BeautifyIcon

# Create Texas map
m = folium.Map(
    location=[31.0, -99.0],
    zoom_start=6
)

# Add SBA locations as stars
for _, row in texas_sba.iterrows():

    icon_star = BeautifyIcon(
        icon='star',
        inner_icon_style='color:red;font-size:10px;',
        background_color='transparent',
        border_color='transparent'
    )

    folium.Marker(
        location=[
            row["latitude"],
            row["longitude"]
        ],

        icon=icon_star,

        popup=(
            f"<b>Disaster:</b> {row['disaster_number']}<br>"
            f"<b>County:</b> {row['county_name']}<br>"
            f"<b>County Type:</b> {row['county_type']}<br>"
            f"<b>Description:</b> {row['disaster_description']}<br>"
            f"<b>Declaration Date:</b> {row['declaration_date']}"
        )

    ).add_to(m)

m

## CSV to JSON

In [121]:
import csv
import json

def csv_to_json(csv_file_path, json_file_path):

    # Empty list to store all CSV rows
    data = []

    # Open the CSV file
    with open(csv_file_path, encoding="utf-8") as csv_file:

        csv_reader = csv.DictReader(csv_file)

        # Read one row at a time
        for row in csv_reader:

            # Add each row to the list
            data.append(row)

    # Create the JSON file
    with open(json_file_path, "w", encoding="utf-8") as json_file:

        json.dump(
            data,
            json_file,
            indent=4
        )


# File locations
csv_file_path = r"Data/SBA_disaster_Final.csv"

json_file_path = r"Data/SBA_disaster_Final.json"

# Run the function
csv_to_json(
    csv_file_path,
    json_file_path
)

print("JSON file created.")

JSON file created.